/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.openapitools.client.model.UsageThresholdObject;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AppliedUsageThresholdObject
 */
class AppliedUsageThresholdObjectTest {
    private final AppliedUsageThresholdObject model = new AppliedUsageThresholdObject();

    /**
     * Model tests for AppliedUsageThresholdObject
     */
    @Test
    void testAppliedUsageThresholdObject() {
        // TODO: test AppliedUsageThresholdObject
    }

    /**
     * Test the property 'lifetimeUsageAmountCents'
     */
    @Test
    void lifetimeUsageAmountCentsTest() {
        // TODO: test lifetimeUsageAmountCents
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'usageThreshold'
     */
    @Test
    void usageThresholdTest() {
        // TODO: test usageThreshold
    }

}
