/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.BillableMetricFilterObject;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BillableMetricObject
 */
class BillableMetricObjectTest {
    private final BillableMetricObject model = new BillableMetricObject();

    /**
     * Model tests for BillableMetricObject
     */
    @Test
    void testBillableMetricObject() {
        // TODO: test BillableMetricObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'recurring'
     */
    @Test
    void recurringTest() {
        // TODO: test recurring
    }

    /**
     * Test the property 'roundingFunction'
     */
    @Test
    void roundingFunctionTest() {
        // TODO: test roundingFunction
    }

    /**
     * Test the property 'roundingPrecision'
     */
    @Test
    void roundingPrecisionTest() {
        // TODO: test roundingPrecision
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expression'
     */
    @Test
    void expressionTest() {
        // TODO: test expression
    }

    /**
     * Test the property 'fieldName'
     */
    @Test
    void fieldNameTest() {
        // TODO: test fieldName
    }

    /**
     * Test the property 'aggregationType'
     */
    @Test
    void aggregationTypeTest() {
        // TODO: test aggregationType
    }

    /**
     * Test the property 'weightedInterval'
     */
    @Test
    void weightedIntervalTest() {
        // TODO: test weightedInterval
    }

    /**
     * Test the property 'filters'
     */
    @Test
    void filtersTest() {
        // TODO: test filters
    }

}
