/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CountryOrNull
 */
class CountryOrNullTest {
    /**
     * Model tests for CountryOrNull
     */
    @Test
    void testCountryOrNull() {
        // TODO: test CountryOrNull
    }

}
