/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.CurrencyOrNull;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CouponObject
 */
class CouponObjectTest {
    private final CouponObject model = new CouponObject();

    /**
     * Model tests for CouponObject
     */
    @Test
    void testCouponObject() {
        // TODO: test CouponObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'couponType'
     */
    @Test
    void couponTypeTest() {
        // TODO: test couponType
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'reusable'
     */
    @Test
    void reusableTest() {
        // TODO: test reusable
    }

    /**
     * Test the property 'limitedPlans'
     */
    @Test
    void limitedPlansTest() {
        // TODO: test limitedPlans
    }

    /**
     * Test the property 'planCodes'
     */
    @Test
    void planCodesTest() {
        // TODO: test planCodes
    }

    /**
     * Test the property 'limitedBillableMetrics'
     */
    @Test
    void limitedBillableMetricsTest() {
        // TODO: test limitedBillableMetrics
    }

    /**
     * Test the property 'billableMetricCodes'
     */
    @Test
    void billableMetricCodesTest() {
        // TODO: test billableMetricCodes
    }

    /**
     * Test the property 'percentageRate'
     */
    @Test
    void percentageRateTest() {
        // TODO: test percentageRate
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'frequencyDuration'
     */
    @Test
    void frequencyDurationTest() {
        // TODO: test frequencyDuration
    }

    /**
     * Test the property 'expiration'
     */
    @Test
    void expirationTest() {
        // TODO: test expiration
    }

    /**
     * Test the property 'expirationAt'
     */
    @Test
    void expirationAtTest() {
        // TODO: test expirationAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'terminatedAt'
     */
    @Test
    void terminatedAtTest() {
        // TODO: test terminatedAt
    }

}
