/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.openapitools.client.model.CreditObjectInvoice;
import org.openapitools.client.model.CreditObjectItem;
import org.openapitools.client.model.Currency;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreditObject
 */
class CreditObjectTest {
    private final CreditObject model = new CreditObject();

    /**
     * Model tests for CreditObject
     */
    @Test
    void testCreditObject() {
        // TODO: test CreditObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'beforeTaxes'
     */
    @Test
    void beforeTaxesTest() {
        // TODO: test beforeTaxes
    }

    /**
     * Test the property 'item'
     */
    @Test
    void itemTest() {
        // TODO: test item
    }

    /**
     * Test the property 'invoice'
     */
    @Test
    void invoiceTest() {
        // TODO: test invoice
    }

}
