/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.CreditNoteEstimatedEstimatedCreditNoteAppliedTaxesInner;
import org.openapitools.client.model.CreditNoteEstimatedEstimatedCreditNoteItemsInner;
import org.openapitools.client.model.Currency;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreditNoteEstimatedEstimatedCreditNote
 */
class CreditNoteEstimatedEstimatedCreditNoteTest {
    private final CreditNoteEstimatedEstimatedCreditNote model = new CreditNoteEstimatedEstimatedCreditNote();

    /**
     * Model tests for CreditNoteEstimatedEstimatedCreditNote
     */
    @Test
    void testCreditNoteEstimatedEstimatedCreditNote() {
        // TODO: test CreditNoteEstimatedEstimatedCreditNote
    }

    /**
     * Test the property 'lagoInvoiceId'
     */
    @Test
    void lagoInvoiceIdTest() {
        // TODO: test lagoInvoiceId
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'taxesAmountCents'
     */
    @Test
    void taxesAmountCentsTest() {
        // TODO: test taxesAmountCents
    }

    /**
     * Test the property 'taxesRate'
     */
    @Test
    void taxesRateTest() {
        // TODO: test taxesRate
    }

    /**
     * Test the property 'subTotalExcludingTaxesAmountCents'
     */
    @Test
    void subTotalExcludingTaxesAmountCentsTest() {
        // TODO: test subTotalExcludingTaxesAmountCents
    }

    /**
     * Test the property 'maxCreditableAmountCents'
     */
    @Test
    void maxCreditableAmountCentsTest() {
        // TODO: test maxCreditableAmountCents
    }

    /**
     * Test the property 'maxRefundableAmountCents'
     */
    @Test
    void maxRefundableAmountCentsTest() {
        // TODO: test maxRefundableAmountCents
    }

    /**
     * Test the property 'couponsAdjustmentAmountCents'
     */
    @Test
    void couponsAdjustmentAmountCentsTest() {
        // TODO: test couponsAdjustmentAmountCents
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'appliedTaxes'
     */
    @Test
    void appliedTaxesTest() {
        // TODO: test appliedTaxes
    }

}
