/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CustomerObject;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerUpdatedRequest
 */
class CustomerUpdatedRequestTest {
    private final CustomerUpdatedRequest model = new CustomerUpdatedRequest();

    /**
     * Model tests for CustomerUpdatedRequest
     */
    @Test
    void testCustomerUpdatedRequest() {
        // TODO: test CustomerUpdatedRequest
    }

    /**
     * Test the property 'webhookType'
     */
    @Test
    void webhookTypeTest() {
        // TODO: test webhookType
    }

    /**
     * Test the property 'objectType'
     */
    @Test
    void objectTypeTest() {
        // TODO: test objectType
    }

    /**
     * Test the property 'customer'
     */
    @Test
    void customerTest() {
        // TODO: test customer
    }

}
