/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.CustomerChargeUsageObject;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomerUsageObject
 */
class CustomerUsageObjectTest {
    private final CustomerUsageObject model = new CustomerUsageObject();

    /**
     * Model tests for CustomerUsageObject
     */
    @Test
    void testCustomerUsageObject() {
        // TODO: test CustomerUsageObject
    }

    /**
     * Test the property 'fromDatetime'
     */
    @Test
    void fromDatetimeTest() {
        // TODO: test fromDatetime
    }

    /**
     * Test the property 'toDatetime'
     */
    @Test
    void toDatetimeTest() {
        // TODO: test toDatetime
    }

    /**
     * Test the property 'issuingDate'
     */
    @Test
    void issuingDateTest() {
        // TODO: test issuingDate
    }

    /**
     * Test the property 'lagoInvoiceId'
     */
    @Test
    void lagoInvoiceIdTest() {
        // TODO: test lagoInvoiceId
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'taxesAmountCents'
     */
    @Test
    void taxesAmountCentsTest() {
        // TODO: test taxesAmountCents
    }

    /**
     * Test the property 'totalAmountCents'
     */
    @Test
    void totalAmountCentsTest() {
        // TODO: test totalAmountCents
    }

    /**
     * Test the property 'chargesUsage'
     */
    @Test
    void chargesUsageTest() {
        // TODO: test chargesUsage
    }

}
