/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FeeAmountDetailsGraduatedPercentageRangesInner
 */
class FeeAmountDetailsGraduatedPercentageRangesInnerTest {
    private final FeeAmountDetailsGraduatedPercentageRangesInner model = new FeeAmountDetailsGraduatedPercentageRangesInner();

    /**
     * Model tests for FeeAmountDetailsGraduatedPercentageRangesInner
     */
    @Test
    void testFeeAmountDetailsGraduatedPercentageRangesInner() {
        // TODO: test FeeAmountDetailsGraduatedPercentageRangesInner
    }

    /**
     * Test the property 'units'
     */
    @Test
    void unitsTest() {
        // TODO: test units
    }

    /**
     * Test the property 'fromValue'
     */
    @Test
    void fromValueTest() {
        // TODO: test fromValue
    }

    /**
     * Test the property 'toValue'
     */
    @Test
    void toValueTest() {
        // TODO: test toValue
    }

    /**
     * Test the property 'flatUnitAmount'
     */
    @Test
    void flatUnitAmountTest() {
        // TODO: test flatUnitAmount
    }

    /**
     * Test the property 'rate'
     */
    @Test
    void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'perUnitTotalAmount'
     */
    @Test
    void perUnitTotalAmountTest() {
        // TODO: test perUnitTotalAmount
    }

    /**
     * Test the property 'totalWithFlatAmount'
     */
    @Test
    void totalWithFlatAmountTest() {
        // TODO: test totalWithFlatAmount
    }

}
