/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoicePreviewInputSubscriptions
 */
class InvoicePreviewInputSubscriptionsTest {
    private final InvoicePreviewInputSubscriptions model = new InvoicePreviewInputSubscriptions();

    /**
     * Model tests for InvoicePreviewInputSubscriptions
     */
    @Test
    void testInvoicePreviewInputSubscriptions() {
        // TODO: test InvoicePreviewInputSubscriptions
    }

    /**
     * Test the property 'externalIds'
     */
    @Test
    void externalIdsTest() {
        // TODO: test externalIds
    }

    /**
     * Test the property 'planCode'
     */
    @Test
    void planCodeTest() {
        // TODO: test planCode
    }

    /**
     * Test the property 'terminatedAt'
     */
    @Test
    void terminatedAtTest() {
        // TODO: test terminatedAt
    }

}
