/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.AppliedUsageThresholdObject;
import org.openapitools.client.model.BillingPeriodObject;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.CustomerObject;
import org.openapitools.client.model.InvoiceAppliedTaxObject;
import org.openapitools.client.model.InvoiceMetadataObject;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceObject
 */
class InvoiceObjectTest {
    private final InvoiceObject model = new InvoiceObject();

    /**
     * Model tests for InvoiceObject
     */
    @Test
    void testInvoiceObject() {
        // TODO: test InvoiceObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'billingEntityCode'
     */
    @Test
    void billingEntityCodeTest() {
        // TODO: test billingEntityCode
    }

    /**
     * Test the property 'sequentialId'
     */
    @Test
    void sequentialIdTest() {
        // TODO: test sequentialId
    }

    /**
     * Test the property 'number'
     */
    @Test
    void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'issuingDate'
     */
    @Test
    void issuingDateTest() {
        // TODO: test issuingDate
    }

    /**
     * Test the property 'paymentDisputeLostAt'
     */
    @Test
    void paymentDisputeLostAtTest() {
        // TODO: test paymentDisputeLostAt
    }

    /**
     * Test the property 'paymentDueDate'
     */
    @Test
    void paymentDueDateTest() {
        // TODO: test paymentDueDate
    }

    /**
     * Test the property 'paymentOverdue'
     */
    @Test
    void paymentOverdueTest() {
        // TODO: test paymentOverdue
    }

    /**
     * Test the property 'netPaymentTerm'
     */
    @Test
    void netPaymentTermTest() {
        // TODO: test netPaymentTerm
    }

    /**
     * Test the property 'invoiceType'
     */
    @Test
    void invoiceTypeTest() {
        // TODO: test invoiceType
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'feesAmountCents'
     */
    @Test
    void feesAmountCentsTest() {
        // TODO: test feesAmountCents
    }

    /**
     * Test the property 'couponsAmountCents'
     */
    @Test
    void couponsAmountCentsTest() {
        // TODO: test couponsAmountCents
    }

    /**
     * Test the property 'creditNotesAmountCents'
     */
    @Test
    void creditNotesAmountCentsTest() {
        // TODO: test creditNotesAmountCents
    }

    /**
     * Test the property 'subTotalExcludingTaxesAmountCents'
     */
    @Test
    void subTotalExcludingTaxesAmountCentsTest() {
        // TODO: test subTotalExcludingTaxesAmountCents
    }

    /**
     * Test the property 'taxesAmountCents'
     */
    @Test
    void taxesAmountCentsTest() {
        // TODO: test taxesAmountCents
    }

    /**
     * Test the property 'subTotalIncludingTaxesAmountCents'
     */
    @Test
    void subTotalIncludingTaxesAmountCentsTest() {
        // TODO: test subTotalIncludingTaxesAmountCents
    }

    /**
     * Test the property 'prepaidCreditAmountCents'
     */
    @Test
    void prepaidCreditAmountCentsTest() {
        // TODO: test prepaidCreditAmountCents
    }

    /**
     * Test the property 'progressiveBillingCreditAmountCents'
     */
    @Test
    void progressiveBillingCreditAmountCentsTest() {
        // TODO: test progressiveBillingCreditAmountCents
    }

    /**
     * Test the property 'totalAmountCents'
     */
    @Test
    void totalAmountCentsTest() {
        // TODO: test totalAmountCents
    }

    /**
     * Test the property 'versionNumber'
     */
    @Test
    void versionNumberTest() {
        // TODO: test versionNumber
    }

    /**
     * Test the property 'selfBilled'
     */
    @Test
    void selfBilledTest() {
        // TODO: test selfBilled
    }

    /**
     * Test the property 'fileUrl'
     */
    @Test
    void fileUrlTest() {
        // TODO: test fileUrl
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'customer'
     */
    @Test
    void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'billingPeriod'
     */
    @Test
    void billingPeriodTest() {
        // TODO: test billingPeriod
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'appliedTaxes'
     */
    @Test
    void appliedTaxesTest() {
        // TODO: test appliedTaxes
    }

    /**
     * Test the property 'appliedUsageThresholds'
     */
    @Test
    void appliedUsageThresholdsTest() {
        // TODO: test appliedUsageThresholds
    }

}
