/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InvoiceCustomSectionObject
 */
class InvoiceCustomSectionObjectTest {
    private final InvoiceCustomSectionObject model = new InvoiceCustomSectionObject();

    /**
     * Model tests for InvoiceCustomSectionObject
     */
    @Test
    void testInvoiceCustomSectionObject() {
        // TODO: test InvoiceCustomSectionObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'details'
     */
    @Test
    void detailsTest() {
        // TODO: test details
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'appliedToOrganization'
     */
    @Test
    void appliedToOrganizationTest() {
        // TODO: test appliedToOrganization
    }

    /**
     * Test the property 'organizationId'
     */
    @Test
    void organizationIdTest() {
        // TODO: test organizationId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
