/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LifetimeUsageThresholdObject
 */
class LifetimeUsageThresholdObjectTest {
    private final LifetimeUsageThresholdObject model = new LifetimeUsageThresholdObject();

    /**
     * Model tests for LifetimeUsageThresholdObject
     */
    @Test
    void testLifetimeUsageThresholdObject() {
        // TODO: test LifetimeUsageThresholdObject
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'completionRatio'
     */
    @Test
    void completionRatioTest() {
        // TODO: test completionRatio
    }

    /**
     * Test the property 'reachedAt'
     */
    @Test
    void reachedAtTest() {
        // TODO: test reachedAt
    }

}
