/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.PaginationMeta;
import org.openapitools.client.model.PaymentReceiptObject;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentReceiptsPaginated
 */
class PaymentReceiptsPaginatedTest {
    private final PaymentReceiptsPaginated model = new PaymentReceiptsPaginated();

    /**
     * Model tests for PaymentReceiptsPaginated
     */
    @Test
    void testPaymentReceiptsPaginated() {
        // TODO: test PaymentReceiptsPaginated
    }

    /**
     * Test the property 'paymentReceipts'
     */
    @Test
    void paymentReceiptsTest() {
        // TODO: test paymentReceipts
    }

    /**
     * Test the property 'meta'
     */
    @Test
    void metaTest() {
        // TODO: test meta
    }

}
