/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.CustomerBaseObject;
import org.openapitools.client.model.InvoiceBaseObject;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentRequestObject
 */
class PaymentRequestObjectTest {
    private final PaymentRequestObject model = new PaymentRequestObject();

    /**
     * Model tests for PaymentRequestObject
     */
    @Test
    void testPaymentRequestObject() {
        // TODO: test PaymentRequestObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'customer'
     */
    @Test
    void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'invoices'
     */
    @Test
    void invoicesTest() {
        // TODO: test invoices
    }

}
