/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.CustomerIntegratrionErrorObjectProviderError;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentRequestPaymentFailureObject
 */
class PaymentRequestPaymentFailureObjectTest {
    private final PaymentRequestPaymentFailureObject model = new PaymentRequestPaymentFailureObject();

    /**
     * Model tests for PaymentRequestPaymentFailureObject
     */
    @Test
    void testPaymentRequestPaymentFailureObject() {
        // TODO: test PaymentRequestPaymentFailureObject
    }

    /**
     * Test the property 'lagoPaymentRequestId'
     */
    @Test
    void lagoPaymentRequestIdTest() {
        // TODO: test lagoPaymentRequestId
    }

    /**
     * Test the property 'lagoInvoiceIds'
     */
    @Test
    void lagoInvoiceIdsTest() {
        // TODO: test lagoInvoiceIds
    }

    /**
     * Test the property 'lagoCustomerId'
     */
    @Test
    void lagoCustomerIdTest() {
        // TODO: test lagoCustomerId
    }

    /**
     * Test the property 'externalCustomerId'
     */
    @Test
    void externalCustomerIdTest() {
        // TODO: test externalCustomerId
    }

    /**
     * Test the property 'providerCustomerId'
     */
    @Test
    void providerCustomerIdTest() {
        // TODO: test providerCustomerId
    }

    /**
     * Test the property 'paymentProvider'
     */
    @Test
    void paymentProviderTest() {
        // TODO: test paymentProvider
    }

    /**
     * Test the property 'paymentProviderCode'
     */
    @Test
    void paymentProviderCodeTest() {
        // TODO: test paymentProviderCode
    }

    /**
     * Test the property 'providerError'
     */
    @Test
    void providerErrorTest() {
        // TODO: test providerError
    }

}
