/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentManualObject
 */
class PaymentManualObjectTest {
    private final PaymentManualObject model = new PaymentManualObject();

    /**
     * Model tests for PaymentManualObject
     */
    @Test
    void testPaymentManualObject() {
        // TODO: test PaymentManualObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'invoiceIds'
     */
    @Test
    void invoiceIdsTest() {
        // TODO: test invoiceIds
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'paymentStatus'
     */
    @Test
    void paymentStatusTest() {
        // TODO: test paymentStatus
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'reference'
     */
    @Test
    void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'externalPaymentId'
     */
    @Test
    void externalPaymentIdTest() {
        // TODO: test externalPaymentId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
