/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaymentCreateInputPayment
 */
class PaymentCreateInputPaymentTest {
    private final PaymentCreateInputPayment model = new PaymentCreateInputPayment();

    /**
     * Model tests for PaymentCreateInputPayment
     */
    @Test
    void testPaymentCreateInputPayment() {
        // TODO: test PaymentCreateInputPayment
    }

    /**
     * Test the property 'invoiceId'
     */
    @Test
    void invoiceIdTest() {
        // TODO: test invoiceId
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'reference'
     */
    @Test
    void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'paidAt'
     */
    @Test
    void paidAtTest() {
        // TODO: test paidAt
    }

}
