/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.ChargeObject;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.MinimumCommitmentObject;
import org.openapitools.client.model.TaxObject;
import org.openapitools.client.model.UsageThresholdObject;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlanObject
 */
class PlanObjectTest {
    private final PlanObject model = new PlanObject();

    /**
     * Model tests for PlanObject
     */
    @Test
    void testPlanObject() {
        // TODO: test PlanObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'invoiceDisplayName'
     */
    @Test
    void invoiceDisplayNameTest() {
        // TODO: test invoiceDisplayName
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'interval'
     */
    @Test
    void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'amountCurrency'
     */
    @Test
    void amountCurrencyTest() {
        // TODO: test amountCurrency
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    void trialPeriodTest() {
        // TODO: test trialPeriod
    }

    /**
     * Test the property 'payInAdvance'
     */
    @Test
    void payInAdvanceTest() {
        // TODO: test payInAdvance
    }

    /**
     * Test the property 'billChargesMonthly'
     */
    @Test
    void billChargesMonthlyTest() {
        // TODO: test billChargesMonthly
    }

    /**
     * Test the property 'minimumCommitment'
     */
    @Test
    void minimumCommitmentTest() {
        // TODO: test minimumCommitment
    }

    /**
     * Test the property 'charges'
     */
    @Test
    void chargesTest() {
        // TODO: test charges
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'usageThresholds'
     */
    @Test
    void usageThresholdsTest() {
        // TODO: test usageThresholds
    }

}
