/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalletTransactionPaymentUrlWalletTransactionPaymentDetails
 */
class WalletTransactionPaymentUrlWalletTransactionPaymentDetailsTest {
    private final WalletTransactionPaymentUrlWalletTransactionPaymentDetails model = new WalletTransactionPaymentUrlWalletTransactionPaymentDetails();

    /**
     * Model tests for WalletTransactionPaymentUrlWalletTransactionPaymentDetails
     */
    @Test
    void testWalletTransactionPaymentUrlWalletTransactionPaymentDetails() {
        // TODO: test WalletTransactionPaymentUrlWalletTransactionPaymentDetails
    }

    /**
     * Test the property 'lagoCustomerId'
     */
    @Test
    void lagoCustomerIdTest() {
        // TODO: test lagoCustomerId
    }

    /**
     * Test the property 'lagoWalletTransactionId'
     */
    @Test
    void lagoWalletTransactionIdTest() {
        // TODO: test lagoWalletTransactionId
    }

    /**
     * Test the property 'externalCustomerId'
     */
    @Test
    void externalCustomerIdTest() {
        // TODO: test externalCustomerId
    }

    /**
     * Test the property 'paymentProvider'
     */
    @Test
    void paymentProviderTest() {
        // TODO: test paymentProvider
    }

    /**
     * Test the property 'paymentUrl'
     */
    @Test
    void paymentUrlTest() {
        // TODO: test paymentUrl
    }

}
