/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Currency;
import org.openapitools.client.model.WalletRecurringTransactionRule;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalletObject
 */
class WalletObjectTest {
    private final WalletObject model = new WalletObject();

    /**
     * Model tests for WalletObject
     */
    @Test
    void testWalletObject() {
        // TODO: test WalletObject
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'lagoCustomerId'
     */
    @Test
    void lagoCustomerIdTest() {
        // TODO: test lagoCustomerId
    }

    /**
     * Test the property 'externalCustomerId'
     */
    @Test
    void externalCustomerIdTest() {
        // TODO: test externalCustomerId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'rateAmount'
     */
    @Test
    void rateAmountTest() {
        // TODO: test rateAmount
    }

    /**
     * Test the property 'creditsBalance'
     */
    @Test
    void creditsBalanceTest() {
        // TODO: test creditsBalance
    }

    /**
     * Test the property 'balanceCents'
     */
    @Test
    void balanceCentsTest() {
        // TODO: test balanceCents
    }

    /**
     * Test the property 'consumedCredits'
     */
    @Test
    void consumedCreditsTest() {
        // TODO: test consumedCredits
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expirationAt'
     */
    @Test
    void expirationAtTest() {
        // TODO: test expirationAt
    }

    /**
     * Test the property 'lastBalanceSyncAt'
     */
    @Test
    void lastBalanceSyncAtTest() {
        // TODO: test lastBalanceSyncAt
    }

    /**
     * Test the property 'lastConsumedCreditAt'
     */
    @Test
    void lastConsumedCreditAtTest() {
        // TODO: test lastConsumedCreditAt
    }

    /**
     * Test the property 'terminatedAt'
     */
    @Test
    void terminatedAtTest() {
        // TODO: test terminatedAt
    }

    /**
     * Test the property 'invoiceRequiresSuccessfulPayment'
     */
    @Test
    void invoiceRequiresSuccessfulPaymentTest() {
        // TODO: test invoiceRequiresSuccessfulPayment
    }

    /**
     * Test the property 'recurringTransactionRules'
     */
    @Test
    void recurringTransactionRulesTest() {
        // TODO: test recurringTransactionRules
    }

    /**
     * Test the property 'ongoingBalanceCents'
     */
    @Test
    void ongoingBalanceCentsTest() {
        // TODO: test ongoingBalanceCents
    }

    /**
     * Test the property 'ongoingUsageBalanceCents'
     */
    @Test
    void ongoingUsageBalanceCentsTest() {
        // TODO: test ongoingUsageBalanceCents
    }

    /**
     * Test the property 'creditsOngoingBalance'
     */
    @Test
    void creditsOngoingBalanceTest() {
        // TODO: test creditsOngoingBalance
    }

    /**
     * Test the property 'creditsOngoingUsageBalance'
     */
    @Test
    void creditsOngoingUsageBalanceTest() {
        // TODO: test creditsOngoingUsageBalance
    }

}
