/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.WalletRecurringTransactionRuleTransactionMetadataInner;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WalletRecurringTransactionRule
 */
class WalletRecurringTransactionRuleTest {
    private final WalletRecurringTransactionRule model = new WalletRecurringTransactionRule();

    /**
     * Model tests for WalletRecurringTransactionRule
     */
    @Test
    void testWalletRecurringTransactionRule() {
        // TODO: test WalletRecurringTransactionRule
    }

    /**
     * Test the property 'lagoId'
     */
    @Test
    void lagoIdTest() {
        // TODO: test lagoId
    }

    /**
     * Test the property 'trigger'
     */
    @Test
    void triggerTest() {
        // TODO: test trigger
    }

    /**
     * Test the property 'method'
     */
    @Test
    void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'interval'
     */
    @Test
    void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'thresholdCredits'
     */
    @Test
    void thresholdCreditsTest() {
        // TODO: test thresholdCredits
    }

    /**
     * Test the property 'paidCredits'
     */
    @Test
    void paidCreditsTest() {
        // TODO: test paidCredits
    }

    /**
     * Test the property 'grantedCredits'
     */
    @Test
    void grantedCreditsTest() {
        // TODO: test grantedCredits
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'targetOngoingBalance'
     */
    @Test
    void targetOngoingBalanceTest() {
        // TODO: test targetOngoingBalance
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expirationAt'
     */
    @Test
    void expirationAtTest() {
        // TODO: test expirationAt
    }

    /**
     * Test the property 'invoiceRequiresSuccessfulPayment'
     */
    @Test
    void invoiceRequiresSuccessfulPaymentTest() {
        // TODO: test invoiceRequiresSuccessfulPayment
    }

    /**
     * Test the property 'transactionMetadata'
     */
    @Test
    void transactionMetadataTest() {
        // TODO: test transactionMetadata
    }

}
