/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.ChargeProperties;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Values used to apply differentiated pricing based on additional event properties.
 */
@JsonPropertyOrder({
  ChargeFilterInput.JSON_PROPERTY_INVOICE_DISPLAY_NAME,
  ChargeFilterInput.JSON_PROPERTY_PROPERTIES,
  ChargeFilterInput.JSON_PROPERTY_VALUES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class ChargeFilterInput {
  public static final String JSON_PROPERTY_INVOICE_DISPLAY_NAME = "invoice_display_name";
  private JsonNullable<String> invoiceDisplayName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @javax.annotation.Nullable
  private ChargeProperties properties;

  public static final String JSON_PROPERTY_VALUES = "values";
  @javax.annotation.Nullable
  private Map<String, List<String>> values = new HashMap<>();

  public ChargeFilterInput() {
  }

  public ChargeFilterInput invoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    this.invoiceDisplayName = JsonNullable.<String>of(invoiceDisplayName);
    
    return this;
  }

  /**
   * Specifies the name that will be displayed on an invoice. If no value is set for this field, the values of the filter will be used as the default display name.
   * @return invoiceDisplayName
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getInvoiceDisplayName() {
        return invoiceDisplayName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getInvoiceDisplayName_JsonNullable() {
    return invoiceDisplayName;
  }
  
  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  public void setInvoiceDisplayName_JsonNullable(JsonNullable<String> invoiceDisplayName) {
    this.invoiceDisplayName = invoiceDisplayName;
  }

  public void setInvoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    this.invoiceDisplayName = JsonNullable.<String>of(invoiceDisplayName);
  }


  public ChargeFilterInput properties(@javax.annotation.Nullable ChargeProperties properties) {
    
    this.properties = properties;
    return this;
  }

  /**
   * List of all thresholds utilized for calculating the charge.
   * @return properties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ChargeProperties getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@javax.annotation.Nullable ChargeProperties properties) {
    this.properties = properties;
  }


  public ChargeFilterInput values(@javax.annotation.Nullable Map<String, List<String>> values) {
    
    this.values = values;
    return this;
  }

  public ChargeFilterInput putValuesItem(String key, List<String> valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * List of possible filter values. The key and values must match one of the billable metric filters.
   * @return values
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<String>> getValues() {
    return values;
  }


  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValues(@javax.annotation.Nullable Map<String, List<String>> values) {
    this.values = values;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargeFilterInput chargeFilterInput = (ChargeFilterInput) o;
    return equalsNullable(this.invoiceDisplayName, chargeFilterInput.invoiceDisplayName) &&
        Objects.equals(this.properties, chargeFilterInput.properties) &&
        Objects.equals(this.values, chargeFilterInput.values);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(invoiceDisplayName), properties, values);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargeFilterInput {\n");
    sb.append("    invoiceDisplayName: ").append(toIndentedString(invoiceDisplayName)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

