/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomerChargeFiltersUsageObjectInner
 */
@JsonPropertyOrder({
  CustomerChargeFiltersUsageObjectInner.JSON_PROPERTY_UNITS,
  CustomerChargeFiltersUsageObjectInner.JSON_PROPERTY_AMOUNT_CENTS,
  CustomerChargeFiltersUsageObjectInner.JSON_PROPERTY_EVENTS_COUNT,
  CustomerChargeFiltersUsageObjectInner.JSON_PROPERTY_INVOICE_DISPLAY_NAME,
  CustomerChargeFiltersUsageObjectInner.JSON_PROPERTY_VALUES
})
@JsonTypeName("CustomerChargeFiltersUsageObject_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class CustomerChargeFiltersUsageObjectInner {
  public static final String JSON_PROPERTY_UNITS = "units";
  @javax.annotation.Nullable
  private String units;

  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amount_cents";
  @javax.annotation.Nullable
  private Integer amountCents;

  public static final String JSON_PROPERTY_EVENTS_COUNT = "events_count";
  @javax.annotation.Nullable
  private Integer eventsCount;

  public static final String JSON_PROPERTY_INVOICE_DISPLAY_NAME = "invoice_display_name";
  @javax.annotation.Nullable
  private String invoiceDisplayName;

  public static final String JSON_PROPERTY_VALUES = "values";
  @javax.annotation.Nullable
  private Map<String, String> values = new HashMap<>();

  public CustomerChargeFiltersUsageObjectInner() {
  }

  public CustomerChargeFiltersUsageObjectInner units(@javax.annotation.Nullable String units) {
    
    this.units = units;
    return this;
  }

  /**
   * The number of units consumed for a specific charge filter related to a charge item.
   * @return units
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnits() {
    return units;
  }


  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnits(@javax.annotation.Nullable String units) {
    this.units = units;
  }


  public CustomerChargeFiltersUsageObjectInner amountCents(@javax.annotation.Nullable Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * The amount in cents, tax excluded, consumed for a specific charge filter related to a charge item.
   * @return amountCents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountCents(@javax.annotation.Nullable Integer amountCents) {
    this.amountCents = amountCents;
  }


  public CustomerChargeFiltersUsageObjectInner eventsCount(@javax.annotation.Nullable Integer eventsCount) {
    
    this.eventsCount = eventsCount;
    return this;
  }

  /**
   * The quantity of usage events that have been recorded for a particular charge filter during the specified time period. These events may also be referred to as the number of transactions in some contexts.
   * @return eventsCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getEventsCount() {
    return eventsCount;
  }


  @JsonProperty(JSON_PROPERTY_EVENTS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventsCount(@javax.annotation.Nullable Integer eventsCount) {
    this.eventsCount = eventsCount;
  }


  public CustomerChargeFiltersUsageObjectInner invoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    
    this.invoiceDisplayName = invoiceDisplayName;
    return this;
  }

  /**
   * Specifies the name that will be displayed on an invoice.
   * @return invoiceDisplayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInvoiceDisplayName() {
    return invoiceDisplayName;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    this.invoiceDisplayName = invoiceDisplayName;
  }


  public CustomerChargeFiltersUsageObjectInner values(@javax.annotation.Nullable Map<String, String> values) {
    
    this.values = values;
    return this;
  }

  public CustomerChargeFiltersUsageObjectInner putValuesItem(String key, String valuesItem) {
    if (this.values == null) {
      this.values = new HashMap<>();
    }
    this.values.put(key, valuesItem);
    return this;
  }

  /**
   * List of filter values applied to the usage.
   * @return values
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getValues() {
    return values;
  }


  @JsonProperty(JSON_PROPERTY_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValues(@javax.annotation.Nullable Map<String, String> values) {
    this.values = values;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerChargeFiltersUsageObjectInner customerChargeFiltersUsageObjectInner = (CustomerChargeFiltersUsageObjectInner) o;
    return Objects.equals(this.units, customerChargeFiltersUsageObjectInner.units) &&
        Objects.equals(this.amountCents, customerChargeFiltersUsageObjectInner.amountCents) &&
        Objects.equals(this.eventsCount, customerChargeFiltersUsageObjectInner.eventsCount) &&
        Objects.equals(this.invoiceDisplayName, customerChargeFiltersUsageObjectInner.invoiceDisplayName) &&
        Objects.equals(this.values, customerChargeFiltersUsageObjectInner.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(units, amountCents, eventsCount, invoiceDisplayName, values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerChargeFiltersUsageObjectInner {\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    eventsCount: ").append(toIndentedString(eventsCount)).append("\n");
    sb.append("    invoiceDisplayName: ").append(toIndentedString(invoiceDisplayName)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

