/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.CountryOrNull;
import org.openapitools.client.model.CurrencyOrNull;
import org.openapitools.client.model.CustomerBillingConfiguration;
import org.openapitools.client.model.CustomerMetadata;
import org.openapitools.client.model.Timezone;
import org.openapitools.client.model.TimezoneOrNull;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomerBaseObject
 */
@JsonPropertyOrder({
  CustomerBaseObject.JSON_PROPERTY_LAGO_ID,
  CustomerBaseObject.JSON_PROPERTY_SEQUENTIAL_ID,
  CustomerBaseObject.JSON_PROPERTY_SLUG,
  CustomerBaseObject.JSON_PROPERTY_EXTERNAL_ID,
  CustomerBaseObject.JSON_PROPERTY_BILLING_ENTITY_CODE,
  CustomerBaseObject.JSON_PROPERTY_ADDRESS_LINE1,
  CustomerBaseObject.JSON_PROPERTY_ADDRESS_LINE2,
  CustomerBaseObject.JSON_PROPERTY_APPLICABLE_TIMEZONE,
  CustomerBaseObject.JSON_PROPERTY_CITY,
  CustomerBaseObject.JSON_PROPERTY_COUNTRY,
  CustomerBaseObject.JSON_PROPERTY_CURRENCY,
  CustomerBaseObject.JSON_PROPERTY_EMAIL,
  CustomerBaseObject.JSON_PROPERTY_LEGAL_NAME,
  CustomerBaseObject.JSON_PROPERTY_LEGAL_NUMBER,
  CustomerBaseObject.JSON_PROPERTY_LOGO_URL,
  CustomerBaseObject.JSON_PROPERTY_NAME,
  CustomerBaseObject.JSON_PROPERTY_FIRSTNAME,
  CustomerBaseObject.JSON_PROPERTY_LASTNAME,
  CustomerBaseObject.JSON_PROPERTY_ACCOUNT_TYPE,
  CustomerBaseObject.JSON_PROPERTY_CUSTOMER_TYPE,
  CustomerBaseObject.JSON_PROPERTY_PHONE,
  CustomerBaseObject.JSON_PROPERTY_STATE,
  CustomerBaseObject.JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER,
  CustomerBaseObject.JSON_PROPERTY_TIMEZONE,
  CustomerBaseObject.JSON_PROPERTY_URL,
  CustomerBaseObject.JSON_PROPERTY_ZIPCODE,
  CustomerBaseObject.JSON_PROPERTY_NET_PAYMENT_TERM,
  CustomerBaseObject.JSON_PROPERTY_CREATED_AT,
  CustomerBaseObject.JSON_PROPERTY_UPDATED_AT,
  CustomerBaseObject.JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE,
  CustomerBaseObject.JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS,
  CustomerBaseObject.JSON_PROPERTY_BILLING_CONFIGURATION,
  CustomerBaseObject.JSON_PROPERTY_SHIPPING_ADDRESS,
  CustomerBaseObject.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class CustomerBaseObject {
  public static final String JSON_PROPERTY_LAGO_ID = "lago_id";
  @javax.annotation.Nonnull
  private UUID lagoId;

  public static final String JSON_PROPERTY_SEQUENTIAL_ID = "sequential_id";
  @javax.annotation.Nonnull
  private Integer sequentialId;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @javax.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "external_id";
  @javax.annotation.Nonnull
  private String externalId;

  public static final String JSON_PROPERTY_BILLING_ENTITY_CODE = "billing_entity_code";
  @javax.annotation.Nullable
  private String billingEntityCode;

  public static final String JSON_PROPERTY_ADDRESS_LINE1 = "address_line1";
  private JsonNullable<String> addressLine1 = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ADDRESS_LINE2 = "address_line2";
  private JsonNullable<String> addressLine2 = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_APPLICABLE_TIMEZONE = "applicable_timezone";
  @javax.annotation.Nonnull
  private Timezone applicableTimezone;

  public static final String JSON_PROPERTY_CITY = "city";
  private JsonNullable<String> city = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private JsonNullable<CountryOrNull> country = JsonNullable.<CountryOrNull>undefined();

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private JsonNullable<CurrencyOrNull> currency = JsonNullable.<CurrencyOrNull>undefined();

  public static final String JSON_PROPERTY_EMAIL = "email";
  private JsonNullable<String> email = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LEGAL_NAME = "legal_name";
  private JsonNullable<String> legalName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LEGAL_NUMBER = "legal_number";
  private JsonNullable<String> legalNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LOGO_URL = "logo_url";
  private JsonNullable<String> logoUrl = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FIRSTNAME = "firstname";
  private JsonNullable<String> firstname = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LASTNAME = "lastname";
  private JsonNullable<String> lastname = JsonNullable.<String>undefined();

  /**
   * The type of the account. It can have one of the following values: - &#x60;customer&#x60;: the account is a customer. - &#x60;partner&#x60;: the account is a partner.
   */
  public enum AccountTypeEnum {
    CUSTOMER(String.valueOf("customer")),
    
    PARTNER(String.valueOf("partner"));

    private String value;

    AccountTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AccountTypeEnum fromValue(String value) {
      for (AccountTypeEnum b : AccountTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACCOUNT_TYPE = "account_type";
  @javax.annotation.Nullable
  private AccountTypeEnum accountType;

  /**
   * The type of the customer. It can have one of the following values: - &#x60;company&#x60;: the customer is a company. - &#x60;individual&#x60;: the customer is an individual.
   */
  public enum CustomerTypeEnum {
    COMPANY(String.valueOf("company")),
    
    INDIVIDUAL(String.valueOf("individual"));

    private String value;

    CustomerTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CustomerTypeEnum fromValue(String value) {
      for (CustomerTypeEnum b : CustomerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_CUSTOMER_TYPE = "customer_type";
  private JsonNullable<CustomerTypeEnum> customerType = JsonNullable.<CustomerTypeEnum>undefined();

  public static final String JSON_PROPERTY_PHONE = "phone";
  private JsonNullable<String> phone = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STATE = "state";
  private JsonNullable<String> state = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER = "tax_identification_number";
  private JsonNullable<String> taxIdentificationNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  private JsonNullable<TimezoneOrNull> timezone = JsonNullable.<TimezoneOrNull>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  private JsonNullable<String> url = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ZIPCODE = "zipcode";
  private JsonNullable<String> zipcode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_NET_PAYMENT_TERM = "net_payment_term";
  private JsonNullable<Integer> netPaymentTerm = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  /**
   * Specifies how invoices with a zero total amount should be handled: - &#x60;inherit&#x60;: (Default) Follows the organization-level configuration. - &#x60;finalize&#x60;: Invoices are issued and finalized even if the total amount is zero. - &#x60;skip&#x60;: Invoices with a total amount of zero are not finalized.
   */
  public enum FinalizeZeroAmountInvoiceEnum {
    INHERIT(String.valueOf("inherit")),
    
    SKIP(String.valueOf("skip")),
    
    FINALIZE(String.valueOf("finalize"));

    private String value;

    FinalizeZeroAmountInvoiceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FinalizeZeroAmountInvoiceEnum fromValue(String value) {
      for (FinalizeZeroAmountInvoiceEnum b : FinalizeZeroAmountInvoiceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE = "finalize_zero_amount_invoice";
  @javax.annotation.Nullable
  private FinalizeZeroAmountInvoiceEnum finalizeZeroAmountInvoice;

  public static final String JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS = "skip_invoice_custom_sections";
  @javax.annotation.Nullable
  private Boolean skipInvoiceCustomSections;

  public static final String JSON_PROPERTY_BILLING_CONFIGURATION = "billing_configuration";
  @javax.annotation.Nullable
  private CustomerBillingConfiguration billingConfiguration;

  public static final String JSON_PROPERTY_SHIPPING_ADDRESS = "shipping_address";
  @javax.annotation.Nullable
  private Address shippingAddress;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private List<CustomerMetadata> metadata = new ArrayList<>();

  public CustomerBaseObject() {
  }

  public CustomerBaseObject lagoId(@javax.annotation.Nonnull UUID lagoId) {
    
    this.lagoId = lagoId;
    return this;
  }

  /**
   * Unique identifier assigned to the customer within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the customer&#39;s record within the Lago system
   * @return lagoId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoId() {
    return lagoId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoId(@javax.annotation.Nonnull UUID lagoId) {
    this.lagoId = lagoId;
  }


  public CustomerBaseObject sequentialId(@javax.annotation.Nonnull Integer sequentialId) {
    
    this.sequentialId = sequentialId;
    return this;
  }

  /**
   * The unique identifier assigned to the customer within the organization&#39;s scope. This identifier is used to track and reference the customer&#39;s order of creation within the organization&#39;s system. It ensures that each customer has a distinct &#x60;sequential_id&#x60;&#x60; associated with them, allowing for easy identification and sorting based on the order of creation
   * @return sequentialId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEQUENTIAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSequentialId() {
    return sequentialId;
  }


  @JsonProperty(JSON_PROPERTY_SEQUENTIAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequentialId(@javax.annotation.Nonnull Integer sequentialId) {
    this.sequentialId = sequentialId;
  }


  public CustomerBaseObject slug(@javax.annotation.Nonnull String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * A concise and unique identifier for the customer, formed by combining the Organization&#39;s &#x60;name&#x60;, &#x60;id&#x60;, and customer&#39;s &#x60;sequential_id&#x60;
   * @return slug
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public CustomerBaseObject externalId(@javax.annotation.Nonnull String externalId) {
    
    this.externalId = externalId;
    return this;
  }

  /**
   * The customer external unique identifier (provided by your own application)
   * @return externalId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalId() {
    return externalId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalId(@javax.annotation.Nonnull String externalId) {
    this.externalId = externalId;
  }


  public CustomerBaseObject billingEntityCode(@javax.annotation.Nullable String billingEntityCode) {
    
    this.billingEntityCode = billingEntityCode;
    return this;
  }

  /**
   * The unique code of the billing entity associated with the customer.
   * @return billingEntityCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_ENTITY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBillingEntityCode() {
    return billingEntityCode;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_ENTITY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingEntityCode(@javax.annotation.Nullable String billingEntityCode) {
    this.billingEntityCode = billingEntityCode;
  }


  public CustomerBaseObject addressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = JsonNullable.<String>of(addressLine1);
    
    return this;
  }

  /**
   * The first line of the billing address
   * @return addressLine1
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getAddressLine1() {
        return addressLine1.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAddressLine1_JsonNullable() {
    return addressLine1;
  }
  
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  public void setAddressLine1_JsonNullable(JsonNullable<String> addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public void setAddressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = JsonNullable.<String>of(addressLine1);
  }


  public CustomerBaseObject addressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = JsonNullable.<String>of(addressLine2);
    
    return this;
  }

  /**
   * The second line of the billing address
   * @return addressLine2
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getAddressLine2() {
        return addressLine2.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAddressLine2_JsonNullable() {
    return addressLine2;
  }
  
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  public void setAddressLine2_JsonNullable(JsonNullable<String> addressLine2) {
    this.addressLine2 = addressLine2;
  }

  public void setAddressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = JsonNullable.<String>of(addressLine2);
  }


  public CustomerBaseObject applicableTimezone(@javax.annotation.Nonnull Timezone applicableTimezone) {
    
    this.applicableTimezone = applicableTimezone;
    return this;
  }

  /**
   * The customer&#39;s applicable timezone, used for billing purposes in their local time.
   * @return applicableTimezone
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLICABLE_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Timezone getApplicableTimezone() {
    return applicableTimezone;
  }


  @JsonProperty(JSON_PROPERTY_APPLICABLE_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplicableTimezone(@javax.annotation.Nonnull Timezone applicableTimezone) {
    this.applicableTimezone = applicableTimezone;
  }


  public CustomerBaseObject city(@javax.annotation.Nullable String city) {
    this.city = JsonNullable.<String>of(city);
    
    return this;
  }

  /**
   * The city of the customer&#39;s billing address
   * @return city
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getCity() {
        return city.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCity_JsonNullable() {
    return city;
  }
  
  @JsonProperty(JSON_PROPERTY_CITY)
  public void setCity_JsonNullable(JsonNullable<String> city) {
    this.city = city;
  }

  public void setCity(@javax.annotation.Nullable String city) {
    this.city = JsonNullable.<String>of(city);
  }


  public CustomerBaseObject country(@javax.annotation.Nullable CountryOrNull country) {
    this.country = JsonNullable.<CountryOrNull>of(country);
    
    return this;
  }

  /**
   * Country code of the customer&#39;s billing address. Format must be ISO 3166 (alpha-2)
   * @return country
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CountryOrNull getCountry() {
        return country.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CountryOrNull> getCountry_JsonNullable() {
    return country;
  }
  
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  public void setCountry_JsonNullable(JsonNullable<CountryOrNull> country) {
    this.country = country;
  }

  public void setCountry(@javax.annotation.Nullable CountryOrNull country) {
    this.country = JsonNullable.<CountryOrNull>of(country);
  }


  public CustomerBaseObject currency(@javax.annotation.Nullable CurrencyOrNull currency) {
    this.currency = JsonNullable.<CurrencyOrNull>of(currency);
    
    return this;
  }

  /**
   * Currency of the customer. Format must be ISO 4217
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CurrencyOrNull getCurrency() {
        return currency.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CurrencyOrNull> getCurrency_JsonNullable() {
    return currency;
  }
  
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  public void setCurrency_JsonNullable(JsonNullable<CurrencyOrNull> currency) {
    this.currency = currency;
  }

  public void setCurrency(@javax.annotation.Nullable CurrencyOrNull currency) {
    this.currency = JsonNullable.<CurrencyOrNull>of(currency);
  }


  public CustomerBaseObject email(@javax.annotation.Nullable String email) {
    this.email = JsonNullable.<String>of(email);
    
    return this;
  }

  /**
   * The email of the customer
   * @return email
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getEmail() {
        return email.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getEmail_JsonNullable() {
    return email;
  }
  
  @JsonProperty(JSON_PROPERTY_EMAIL)
  public void setEmail_JsonNullable(JsonNullable<String> email) {
    this.email = email;
  }

  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = JsonNullable.<String>of(email);
  }


  public CustomerBaseObject legalName(@javax.annotation.Nullable String legalName) {
    this.legalName = JsonNullable.<String>of(legalName);
    
    return this;
  }

  /**
   * The legal company name of the customer
   * @return legalName
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLegalName() {
        return legalName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLegalName_JsonNullable() {
    return legalName;
  }
  
  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  public void setLegalName_JsonNullable(JsonNullable<String> legalName) {
    this.legalName = legalName;
  }

  public void setLegalName(@javax.annotation.Nullable String legalName) {
    this.legalName = JsonNullable.<String>of(legalName);
  }


  public CustomerBaseObject legalNumber(@javax.annotation.Nullable String legalNumber) {
    this.legalNumber = JsonNullable.<String>of(legalNumber);
    
    return this;
  }

  /**
   * The legal company number of the customer
   * @return legalNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLegalNumber() {
        return legalNumber.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LEGAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLegalNumber_JsonNullable() {
    return legalNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_LEGAL_NUMBER)
  public void setLegalNumber_JsonNullable(JsonNullable<String> legalNumber) {
    this.legalNumber = legalNumber;
  }

  public void setLegalNumber(@javax.annotation.Nullable String legalNumber) {
    this.legalNumber = JsonNullable.<String>of(legalNumber);
  }


  public CustomerBaseObject logoUrl(@javax.annotation.Nullable String logoUrl) {
    this.logoUrl = JsonNullable.<String>of(logoUrl);
    
    return this;
  }

  /**
   * The logo URL of the customer
   * @return logoUrl
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLogoUrl() {
        return logoUrl.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLogoUrl_JsonNullable() {
    return logoUrl;
  }
  
  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  public void setLogoUrl_JsonNullable(JsonNullable<String> logoUrl) {
    this.logoUrl = logoUrl;
  }

  public void setLogoUrl(@javax.annotation.Nullable String logoUrl) {
    this.logoUrl = JsonNullable.<String>of(logoUrl);
  }


  public CustomerBaseObject name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    
    return this;
  }

  /**
   * The full name of the customer
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public CustomerBaseObject firstname(@javax.annotation.Nullable String firstname) {
    this.firstname = JsonNullable.<String>of(firstname);
    
    return this;
  }

  /**
   * First name of the customer
   * @return firstname
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getFirstname() {
        return firstname.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_FIRSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getFirstname_JsonNullable() {
    return firstname;
  }
  
  @JsonProperty(JSON_PROPERTY_FIRSTNAME)
  public void setFirstname_JsonNullable(JsonNullable<String> firstname) {
    this.firstname = firstname;
  }

  public void setFirstname(@javax.annotation.Nullable String firstname) {
    this.firstname = JsonNullable.<String>of(firstname);
  }


  public CustomerBaseObject lastname(@javax.annotation.Nullable String lastname) {
    this.lastname = JsonNullable.<String>of(lastname);
    
    return this;
  }

  /**
   * Last name of the customer
   * @return lastname
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getLastname() {
        return lastname.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LASTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastname_JsonNullable() {
    return lastname;
  }
  
  @JsonProperty(JSON_PROPERTY_LASTNAME)
  public void setLastname_JsonNullable(JsonNullable<String> lastname) {
    this.lastname = lastname;
  }

  public void setLastname(@javax.annotation.Nullable String lastname) {
    this.lastname = JsonNullable.<String>of(lastname);
  }


  public CustomerBaseObject accountType(@javax.annotation.Nullable AccountTypeEnum accountType) {
    
    this.accountType = accountType;
    return this;
  }

  /**
   * The type of the account. It can have one of the following values: - &#x60;customer&#x60;: the account is a customer. - &#x60;partner&#x60;: the account is a partner.
   * @return accountType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountTypeEnum getAccountType() {
    return accountType;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountType(@javax.annotation.Nullable AccountTypeEnum accountType) {
    this.accountType = accountType;
  }


  public CustomerBaseObject customerType(@javax.annotation.Nullable CustomerTypeEnum customerType) {
    this.customerType = JsonNullable.<CustomerTypeEnum>of(customerType);
    
    return this;
  }

  /**
   * The type of the customer. It can have one of the following values: - &#x60;company&#x60;: the customer is a company. - &#x60;individual&#x60;: the customer is an individual.
   * @return customerType
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CustomerTypeEnum getCustomerType() {
        return customerType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOMER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CustomerTypeEnum> getCustomerType_JsonNullable() {
    return customerType;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOMER_TYPE)
  public void setCustomerType_JsonNullable(JsonNullable<CustomerTypeEnum> customerType) {
    this.customerType = customerType;
  }

  public void setCustomerType(@javax.annotation.Nullable CustomerTypeEnum customerType) {
    this.customerType = JsonNullable.<CustomerTypeEnum>of(customerType);
  }


  public CustomerBaseObject phone(@javax.annotation.Nullable String phone) {
    this.phone = JsonNullable.<String>of(phone);
    
    return this;
  }

  /**
   * The phone number of the customer
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPhone() {
        return phone.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPhone_JsonNullable() {
    return phone;
  }
  
  @JsonProperty(JSON_PROPERTY_PHONE)
  public void setPhone_JsonNullable(JsonNullable<String> phone) {
    this.phone = phone;
  }

  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = JsonNullable.<String>of(phone);
  }


  public CustomerBaseObject state(@javax.annotation.Nullable String state) {
    this.state = JsonNullable.<String>of(state);
    
    return this;
  }

  /**
   * The state of the customer&#39;s billing address
   * @return state
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getState() {
        return state.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getState_JsonNullable() {
    return state;
  }
  
  @JsonProperty(JSON_PROPERTY_STATE)
  public void setState_JsonNullable(JsonNullable<String> state) {
    this.state = state;
  }

  public void setState(@javax.annotation.Nullable String state) {
    this.state = JsonNullable.<String>of(state);
  }


  public CustomerBaseObject taxIdentificationNumber(@javax.annotation.Nullable String taxIdentificationNumber) {
    this.taxIdentificationNumber = JsonNullable.<String>of(taxIdentificationNumber);
    
    return this;
  }

  /**
   * The tax identification number of the customer
   * @return taxIdentificationNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getTaxIdentificationNumber() {
        return taxIdentificationNumber.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTaxIdentificationNumber_JsonNullable() {
    return taxIdentificationNumber;
  }
  
  @JsonProperty(JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER)
  public void setTaxIdentificationNumber_JsonNullable(JsonNullable<String> taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
  }

  public void setTaxIdentificationNumber(@javax.annotation.Nullable String taxIdentificationNumber) {
    this.taxIdentificationNumber = JsonNullable.<String>of(taxIdentificationNumber);
  }


  public CustomerBaseObject timezone(@javax.annotation.Nullable TimezoneOrNull timezone) {
    this.timezone = JsonNullable.<TimezoneOrNull>of(timezone);
    
    return this;
  }

  /**
   * The customer&#39;s timezone, used for billing purposes in their local time. Overrides the organization&#39;s timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public TimezoneOrNull getTimezone() {
        return timezone.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TimezoneOrNull> getTimezone_JsonNullable() {
    return timezone;
  }
  
  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  public void setTimezone_JsonNullable(JsonNullable<TimezoneOrNull> timezone) {
    this.timezone = timezone;
  }

  public void setTimezone(@javax.annotation.Nullable TimezoneOrNull timezone) {
    this.timezone = JsonNullable.<TimezoneOrNull>of(timezone);
  }


  public CustomerBaseObject url(@javax.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
    
    return this;
  }

  /**
   * The custom website URL of the customer
   * @return url
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getUrl() {
        return url.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUrl_JsonNullable() {
    return url;
  }
  
  @JsonProperty(JSON_PROPERTY_URL)
  public void setUrl_JsonNullable(JsonNullable<String> url) {
    this.url = url;
  }

  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = JsonNullable.<String>of(url);
  }


  public CustomerBaseObject zipcode(@javax.annotation.Nullable String zipcode) {
    this.zipcode = JsonNullable.<String>of(zipcode);
    
    return this;
  }

  /**
   * The zipcode of the customer&#39;s billing address
   * @return zipcode
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getZipcode() {
        return zipcode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getZipcode_JsonNullable() {
    return zipcode;
  }
  
  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  public void setZipcode_JsonNullable(JsonNullable<String> zipcode) {
    this.zipcode = zipcode;
  }

  public void setZipcode(@javax.annotation.Nullable String zipcode) {
    this.zipcode = JsonNullable.<String>of(zipcode);
  }


  public CustomerBaseObject netPaymentTerm(@javax.annotation.Nullable Integer netPaymentTerm) {
    this.netPaymentTerm = JsonNullable.<Integer>of(netPaymentTerm);
    
    return this;
  }

  /**
   * The net payment term, expressed in days, specifies the duration within which a customer is expected to remit payment after the invoice is finalized.
   * @return netPaymentTerm
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Integer getNetPaymentTerm() {
        return netPaymentTerm.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NET_PAYMENT_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getNetPaymentTerm_JsonNullable() {
    return netPaymentTerm;
  }
  
  @JsonProperty(JSON_PROPERTY_NET_PAYMENT_TERM)
  public void setNetPaymentTerm_JsonNullable(JsonNullable<Integer> netPaymentTerm) {
    this.netPaymentTerm = netPaymentTerm;
  }

  public void setNetPaymentTerm(@javax.annotation.Nullable Integer netPaymentTerm) {
    this.netPaymentTerm = JsonNullable.<Integer>of(netPaymentTerm);
  }


  public CustomerBaseObject createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date of the customer creation, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC). The creation_date provides a standardized and internationally recognized timestamp for when the customer object was created
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CustomerBaseObject updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The date of the customer update, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC). The update_date provides a standardized and internationally recognized timestamp for when the customer object was updated
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public CustomerBaseObject finalizeZeroAmountInvoice(@javax.annotation.Nullable FinalizeZeroAmountInvoiceEnum finalizeZeroAmountInvoice) {
    
    this.finalizeZeroAmountInvoice = finalizeZeroAmountInvoice;
    return this;
  }

  /**
   * Specifies how invoices with a zero total amount should be handled: - &#x60;inherit&#x60;: (Default) Follows the organization-level configuration. - &#x60;finalize&#x60;: Invoices are issued and finalized even if the total amount is zero. - &#x60;skip&#x60;: Invoices with a total amount of zero are not finalized.
   * @return finalizeZeroAmountInvoice
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FinalizeZeroAmountInvoiceEnum getFinalizeZeroAmountInvoice() {
    return finalizeZeroAmountInvoice;
  }


  @JsonProperty(JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinalizeZeroAmountInvoice(@javax.annotation.Nullable FinalizeZeroAmountInvoiceEnum finalizeZeroAmountInvoice) {
    this.finalizeZeroAmountInvoice = finalizeZeroAmountInvoice;
  }


  public CustomerBaseObject skipInvoiceCustomSections(@javax.annotation.Nullable Boolean skipInvoiceCustomSections) {
    
    this.skipInvoiceCustomSections = skipInvoiceCustomSections;
    return this;
  }

  /**
   * Set to true to exclude all invoice custom sections from PDF generation for this customer only.
   * @return skipInvoiceCustomSections
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSkipInvoiceCustomSections() {
    return skipInvoiceCustomSections;
  }


  @JsonProperty(JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkipInvoiceCustomSections(@javax.annotation.Nullable Boolean skipInvoiceCustomSections) {
    this.skipInvoiceCustomSections = skipInvoiceCustomSections;
  }


  public CustomerBaseObject billingConfiguration(@javax.annotation.Nullable CustomerBillingConfiguration billingConfiguration) {
    
    this.billingConfiguration = billingConfiguration;
    return this;
  }

  /**
   * Get billingConfiguration
   * @return billingConfiguration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerBillingConfiguration getBillingConfiguration() {
    return billingConfiguration;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingConfiguration(@javax.annotation.Nullable CustomerBillingConfiguration billingConfiguration) {
    this.billingConfiguration = billingConfiguration;
  }


  public CustomerBaseObject shippingAddress(@javax.annotation.Nullable Address shippingAddress) {
    
    this.shippingAddress = shippingAddress;
    return this;
  }

  /**
   * Get shippingAddress
   * @return shippingAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address getShippingAddress() {
    return shippingAddress;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingAddress(@javax.annotation.Nullable Address shippingAddress) {
    this.shippingAddress = shippingAddress;
  }


  public CustomerBaseObject metadata(@javax.annotation.Nullable List<CustomerMetadata> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public CustomerBaseObject addMetadataItem(CustomerMetadata metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerMetadata> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable List<CustomerMetadata> metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerBaseObject customerBaseObject = (CustomerBaseObject) o;
    return Objects.equals(this.lagoId, customerBaseObject.lagoId) &&
        Objects.equals(this.sequentialId, customerBaseObject.sequentialId) &&
        Objects.equals(this.slug, customerBaseObject.slug) &&
        Objects.equals(this.externalId, customerBaseObject.externalId) &&
        Objects.equals(this.billingEntityCode, customerBaseObject.billingEntityCode) &&
        equalsNullable(this.addressLine1, customerBaseObject.addressLine1) &&
        equalsNullable(this.addressLine2, customerBaseObject.addressLine2) &&
        Objects.equals(this.applicableTimezone, customerBaseObject.applicableTimezone) &&
        equalsNullable(this.city, customerBaseObject.city) &&
        equalsNullable(this.country, customerBaseObject.country) &&
        equalsNullable(this.currency, customerBaseObject.currency) &&
        equalsNullable(this.email, customerBaseObject.email) &&
        equalsNullable(this.legalName, customerBaseObject.legalName) &&
        equalsNullable(this.legalNumber, customerBaseObject.legalNumber) &&
        equalsNullable(this.logoUrl, customerBaseObject.logoUrl) &&
        equalsNullable(this.name, customerBaseObject.name) &&
        equalsNullable(this.firstname, customerBaseObject.firstname) &&
        equalsNullable(this.lastname, customerBaseObject.lastname) &&
        Objects.equals(this.accountType, customerBaseObject.accountType) &&
        equalsNullable(this.customerType, customerBaseObject.customerType) &&
        equalsNullable(this.phone, customerBaseObject.phone) &&
        equalsNullable(this.state, customerBaseObject.state) &&
        equalsNullable(this.taxIdentificationNumber, customerBaseObject.taxIdentificationNumber) &&
        equalsNullable(this.timezone, customerBaseObject.timezone) &&
        equalsNullable(this.url, customerBaseObject.url) &&
        equalsNullable(this.zipcode, customerBaseObject.zipcode) &&
        equalsNullable(this.netPaymentTerm, customerBaseObject.netPaymentTerm) &&
        Objects.equals(this.createdAt, customerBaseObject.createdAt) &&
        Objects.equals(this.updatedAt, customerBaseObject.updatedAt) &&
        Objects.equals(this.finalizeZeroAmountInvoice, customerBaseObject.finalizeZeroAmountInvoice) &&
        Objects.equals(this.skipInvoiceCustomSections, customerBaseObject.skipInvoiceCustomSections) &&
        Objects.equals(this.billingConfiguration, customerBaseObject.billingConfiguration) &&
        Objects.equals(this.shippingAddress, customerBaseObject.shippingAddress) &&
        Objects.equals(this.metadata, customerBaseObject.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(lagoId, sequentialId, slug, externalId, billingEntityCode, hashCodeNullable(addressLine1), hashCodeNullable(addressLine2), applicableTimezone, hashCodeNullable(city), hashCodeNullable(country), hashCodeNullable(currency), hashCodeNullable(email), hashCodeNullable(legalName), hashCodeNullable(legalNumber), hashCodeNullable(logoUrl), hashCodeNullable(name), hashCodeNullable(firstname), hashCodeNullable(lastname), accountType, hashCodeNullable(customerType), hashCodeNullable(phone), hashCodeNullable(state), hashCodeNullable(taxIdentificationNumber), hashCodeNullable(timezone), hashCodeNullable(url), hashCodeNullable(zipcode), hashCodeNullable(netPaymentTerm), createdAt, updatedAt, finalizeZeroAmountInvoice, skipInvoiceCustomSections, billingConfiguration, shippingAddress, metadata);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerBaseObject {\n");
    sb.append("    lagoId: ").append(toIndentedString(lagoId)).append("\n");
    sb.append("    sequentialId: ").append(toIndentedString(sequentialId)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    billingEntityCode: ").append(toIndentedString(billingEntityCode)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    applicableTimezone: ").append(toIndentedString(applicableTimezone)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    legalNumber: ").append(toIndentedString(legalNumber)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    taxIdentificationNumber: ").append(toIndentedString(taxIdentificationNumber)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    zipcode: ").append(toIndentedString(zipcode)).append("\n");
    sb.append("    netPaymentTerm: ").append(toIndentedString(netPaymentTerm)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    finalizeZeroAmountInvoice: ").append(toIndentedString(finalizeZeroAmountInvoice)).append("\n");
    sb.append("    skipInvoiceCustomSections: ").append(toIndentedString(skipInvoiceCustomSections)).append("\n");
    sb.append("    billingConfiguration: ").append(toIndentedString(billingConfiguration)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

