/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.CountryOrNull;
import org.openapitools.client.model.CurrencyOrNull;
import org.openapitools.client.model.CustomerBillingConfiguration;
import org.openapitools.client.model.CustomerMetadata;
import org.openapitools.client.model.IntegrationCustomer;
import org.openapitools.client.model.InvoiceCustomSectionObject;
import org.openapitools.client.model.TaxObject;
import org.openapitools.client.model.Timezone;
import org.openapitools.client.model.TimezoneOrNull;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CustomerObjectExtended
 */
@JsonPropertyOrder({
  CustomerObjectExtended.JSON_PROPERTY_LAGO_ID,
  CustomerObjectExtended.JSON_PROPERTY_SEQUENTIAL_ID,
  CustomerObjectExtended.JSON_PROPERTY_SLUG,
  CustomerObjectExtended.JSON_PROPERTY_EXTERNAL_ID,
  CustomerObjectExtended.JSON_PROPERTY_BILLING_ENTITY_CODE,
  CustomerObjectExtended.JSON_PROPERTY_ADDRESS_LINE1,
  CustomerObjectExtended.JSON_PROPERTY_ADDRESS_LINE2,
  CustomerObjectExtended.JSON_PROPERTY_APPLICABLE_TIMEZONE,
  CustomerObjectExtended.JSON_PROPERTY_CITY,
  CustomerObjectExtended.JSON_PROPERTY_COUNTRY,
  CustomerObjectExtended.JSON_PROPERTY_CURRENCY,
  CustomerObjectExtended.JSON_PROPERTY_EMAIL,
  CustomerObjectExtended.JSON_PROPERTY_LEGAL_NAME,
  CustomerObjectExtended.JSON_PROPERTY_LEGAL_NUMBER,
  CustomerObjectExtended.JSON_PROPERTY_LOGO_URL,
  CustomerObjectExtended.JSON_PROPERTY_NAME,
  CustomerObjectExtended.JSON_PROPERTY_FIRSTNAME,
  CustomerObjectExtended.JSON_PROPERTY_LASTNAME,
  CustomerObjectExtended.JSON_PROPERTY_ACCOUNT_TYPE,
  CustomerObjectExtended.JSON_PROPERTY_CUSTOMER_TYPE,
  CustomerObjectExtended.JSON_PROPERTY_PHONE,
  CustomerObjectExtended.JSON_PROPERTY_STATE,
  CustomerObjectExtended.JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER,
  CustomerObjectExtended.JSON_PROPERTY_TIMEZONE,
  CustomerObjectExtended.JSON_PROPERTY_URL,
  CustomerObjectExtended.JSON_PROPERTY_ZIPCODE,
  CustomerObjectExtended.JSON_PROPERTY_NET_PAYMENT_TERM,
  CustomerObjectExtended.JSON_PROPERTY_CREATED_AT,
  CustomerObjectExtended.JSON_PROPERTY_UPDATED_AT,
  CustomerObjectExtended.JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE,
  CustomerObjectExtended.JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS,
  CustomerObjectExtended.JSON_PROPERTY_BILLING_CONFIGURATION,
  CustomerObjectExtended.JSON_PROPERTY_SHIPPING_ADDRESS,
  CustomerObjectExtended.JSON_PROPERTY_METADATA,
  CustomerObjectExtended.JSON_PROPERTY_INTEGRATION_CUSTOMERS,
  CustomerObjectExtended.JSON_PROPERTY_TAXES,
  CustomerObjectExtended.JSON_PROPERTY_APPLICABLE_INVOICE_CUSTOM_SECTIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class CustomerObjectExtended {
  public static final String JSON_PROPERTY_LAGO_ID = "lago_id";
  @javax.annotation.Nonnull
  private UUID lagoId;

  public static final String JSON_PROPERTY_SEQUENTIAL_ID = "sequential_id";
  @javax.annotation.Nonnull
  private Integer sequentialId;

  public static final String JSON_PROPERTY_SLUG = "slug";
  @javax.annotation.Nonnull
  private String slug;

  public static final String JSON_PROPERTY_EXTERNAL_ID = "external_id";
  @javax.annotation.Nonnull
  private String externalId;

  public static final String JSON_PROPERTY_BILLING_ENTITY_CODE = "billing_entity_code";
  @javax.annotation.Nullable
  private String billingEntityCode;

  public static final String JSON_PROPERTY_ADDRESS_LINE1 = "address_line1";
  @javax.annotation.Nullable
  private String addressLine1;

  public static final String JSON_PROPERTY_ADDRESS_LINE2 = "address_line2";
  @javax.annotation.Nullable
  private String addressLine2;

  public static final String JSON_PROPERTY_APPLICABLE_TIMEZONE = "applicable_timezone";
  @javax.annotation.Nonnull
  private Timezone applicableTimezone;

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private JsonNullable<CountryOrNull> country = JsonNullable.<CountryOrNull>undefined();

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  private JsonNullable<CurrencyOrNull> currency = JsonNullable.<CurrencyOrNull>undefined();

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_LEGAL_NAME = "legal_name";
  @javax.annotation.Nullable
  private String legalName;

  public static final String JSON_PROPERTY_LEGAL_NUMBER = "legal_number";
  @javax.annotation.Nullable
  private String legalNumber;

  public static final String JSON_PROPERTY_LOGO_URL = "logo_url";
  @javax.annotation.Nullable
  private String logoUrl;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_FIRSTNAME = "firstname";
  @javax.annotation.Nullable
  private String firstname;

  public static final String JSON_PROPERTY_LASTNAME = "lastname";
  @javax.annotation.Nullable
  private String lastname;

  /**
   * The type of the account. It can have one of the following values: - &#x60;customer&#x60;: the account is a customer. - &#x60;partner&#x60;: the account is a partner.
   */
  public enum AccountTypeEnum {
    CUSTOMER(String.valueOf("customer")),
    
    PARTNER(String.valueOf("partner"));

    private String value;

    AccountTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AccountTypeEnum fromValue(String value) {
      for (AccountTypeEnum b : AccountTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACCOUNT_TYPE = "account_type";
  @javax.annotation.Nullable
  private AccountTypeEnum accountType;

  /**
   * The type of the customer. It can have one of the following values: - &#x60;company&#x60;: the customer is a company. - &#x60;individual&#x60;: the customer is an individual.
   */
  public enum CustomerTypeEnum {
    COMPANY(String.valueOf("company")),
    
    INDIVIDUAL(String.valueOf("individual"));

    private String value;

    CustomerTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CustomerTypeEnum fromValue(String value) {
      for (CustomerTypeEnum b : CustomerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_CUSTOMER_TYPE = "customer_type";
  private JsonNullable<CustomerTypeEnum> customerType = JsonNullable.<CustomerTypeEnum>undefined();

  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER = "tax_identification_number";
  @javax.annotation.Nullable
  private String taxIdentificationNumber;

  public static final String JSON_PROPERTY_TIMEZONE = "timezone";
  private JsonNullable<TimezoneOrNull> timezone = JsonNullable.<TimezoneOrNull>undefined();

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_ZIPCODE = "zipcode";
  @javax.annotation.Nullable
  private String zipcode;

  public static final String JSON_PROPERTY_NET_PAYMENT_TERM = "net_payment_term";
  @javax.annotation.Nullable
  private Integer netPaymentTerm;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  /**
   * Specifies how invoices with a zero total amount should be handled: - &#x60;inherit&#x60;: (Default) Follows the organization-level configuration. - &#x60;finalize&#x60;: Invoices are issued and finalized even if the total amount is zero. - &#x60;skip&#x60;: Invoices with a total amount of zero are not finalized.
   */
  public enum FinalizeZeroAmountInvoiceEnum {
    INHERIT(String.valueOf("inherit")),
    
    SKIP(String.valueOf("skip")),
    
    FINALIZE(String.valueOf("finalize"));

    private String value;

    FinalizeZeroAmountInvoiceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FinalizeZeroAmountInvoiceEnum fromValue(String value) {
      for (FinalizeZeroAmountInvoiceEnum b : FinalizeZeroAmountInvoiceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE = "finalize_zero_amount_invoice";
  @javax.annotation.Nullable
  private FinalizeZeroAmountInvoiceEnum finalizeZeroAmountInvoice;

  public static final String JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS = "skip_invoice_custom_sections";
  @javax.annotation.Nullable
  private Boolean skipInvoiceCustomSections;

  public static final String JSON_PROPERTY_BILLING_CONFIGURATION = "billing_configuration";
  @javax.annotation.Nullable
  private CustomerBillingConfiguration billingConfiguration;

  public static final String JSON_PROPERTY_SHIPPING_ADDRESS = "shipping_address";
  @javax.annotation.Nullable
  private Address shippingAddress;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private List<CustomerMetadata> metadata = new ArrayList<>();

  public static final String JSON_PROPERTY_INTEGRATION_CUSTOMERS = "integration_customers";
  @javax.annotation.Nullable
  private List<IntegrationCustomer> integrationCustomers = new ArrayList<>();

  public static final String JSON_PROPERTY_TAXES = "taxes";
  @javax.annotation.Nullable
  private List<TaxObject> taxes = new ArrayList<>();

  public static final String JSON_PROPERTY_APPLICABLE_INVOICE_CUSTOM_SECTIONS = "applicable_invoice_custom_sections";
  @javax.annotation.Nullable
  private List<InvoiceCustomSectionObject> applicableInvoiceCustomSections = new ArrayList<>();

  public CustomerObjectExtended() {
  }

  public CustomerObjectExtended lagoId(@javax.annotation.Nonnull UUID lagoId) {
    
    this.lagoId = lagoId;
    return this;
  }

  /**
   * Unique identifier assigned to the customer within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the customer&#39;s record within the Lago system
   * @return lagoId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoId() {
    return lagoId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoId(@javax.annotation.Nonnull UUID lagoId) {
    this.lagoId = lagoId;
  }


  public CustomerObjectExtended sequentialId(@javax.annotation.Nonnull Integer sequentialId) {
    
    this.sequentialId = sequentialId;
    return this;
  }

  /**
   * The unique identifier assigned to the customer within the organization&#39;s scope. This identifier is used to track and reference the customer&#39;s order of creation within the organization&#39;s system. It ensures that each customer has a distinct &#x60;sequential_id&#x60;&#x60; associated with them, allowing for easy identification and sorting based on the order of creation
   * @return sequentialId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEQUENTIAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getSequentialId() {
    return sequentialId;
  }


  @JsonProperty(JSON_PROPERTY_SEQUENTIAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSequentialId(@javax.annotation.Nonnull Integer sequentialId) {
    this.sequentialId = sequentialId;
  }


  public CustomerObjectExtended slug(@javax.annotation.Nonnull String slug) {
    
    this.slug = slug;
    return this;
  }

  /**
   * A concise and unique identifier for the customer, formed by combining the Organization&#39;s &#x60;name&#x60;, &#x60;id&#x60;, and customer&#39;s &#x60;sequential_id&#x60;
   * @return slug
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSlug() {
    return slug;
  }


  @JsonProperty(JSON_PROPERTY_SLUG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public CustomerObjectExtended externalId(@javax.annotation.Nonnull String externalId) {
    
    this.externalId = externalId;
    return this;
  }

  /**
   * The customer external unique identifier (provided by your own application)
   * @return externalId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalId() {
    return externalId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalId(@javax.annotation.Nonnull String externalId) {
    this.externalId = externalId;
  }


  public CustomerObjectExtended billingEntityCode(@javax.annotation.Nullable String billingEntityCode) {
    
    this.billingEntityCode = billingEntityCode;
    return this;
  }

  /**
   * The unique code of the billing entity associated with the customer.
   * @return billingEntityCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_ENTITY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBillingEntityCode() {
    return billingEntityCode;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_ENTITY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingEntityCode(@javax.annotation.Nullable String billingEntityCode) {
    this.billingEntityCode = billingEntityCode;
  }


  public CustomerObjectExtended addressLine1(@javax.annotation.Nullable String addressLine1) {
    
    this.addressLine1 = addressLine1;
    return this;
  }

  /**
   * The first line of the billing address
   * @return addressLine1
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressLine1() {
    return addressLine1;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLine1(@javax.annotation.Nullable String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public CustomerObjectExtended addressLine2(@javax.annotation.Nullable String addressLine2) {
    
    this.addressLine2 = addressLine2;
    return this;
  }

  /**
   * The second line of the billing address
   * @return addressLine2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddressLine2() {
    return addressLine2;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS_LINE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddressLine2(@javax.annotation.Nullable String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public CustomerObjectExtended applicableTimezone(@javax.annotation.Nonnull Timezone applicableTimezone) {
    
    this.applicableTimezone = applicableTimezone;
    return this;
  }

  /**
   * The customer&#39;s applicable timezone, used for billing purposes in their local time.
   * @return applicableTimezone
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_APPLICABLE_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Timezone getApplicableTimezone() {
    return applicableTimezone;
  }


  @JsonProperty(JSON_PROPERTY_APPLICABLE_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApplicableTimezone(@javax.annotation.Nonnull Timezone applicableTimezone) {
    this.applicableTimezone = applicableTimezone;
  }


  public CustomerObjectExtended city(@javax.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * The city of the customer&#39;s billing address
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }


  public CustomerObjectExtended country(@javax.annotation.Nullable CountryOrNull country) {
    this.country = JsonNullable.<CountryOrNull>of(country);
    
    return this;
  }

  /**
   * Country code of the customer&#39;s billing address. Format must be ISO 3166 (alpha-2)
   * @return country
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CountryOrNull getCountry() {
        return country.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CountryOrNull> getCountry_JsonNullable() {
    return country;
  }
  
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  public void setCountry_JsonNullable(JsonNullable<CountryOrNull> country) {
    this.country = country;
  }

  public void setCountry(@javax.annotation.Nullable CountryOrNull country) {
    this.country = JsonNullable.<CountryOrNull>of(country);
  }


  public CustomerObjectExtended currency(@javax.annotation.Nullable CurrencyOrNull currency) {
    this.currency = JsonNullable.<CurrencyOrNull>of(currency);
    
    return this;
  }

  /**
   * Currency of the customer. Format must be ISO 4217
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CurrencyOrNull getCurrency() {
        return currency.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CurrencyOrNull> getCurrency_JsonNullable() {
    return currency;
  }
  
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  public void setCurrency_JsonNullable(JsonNullable<CurrencyOrNull> currency) {
    this.currency = currency;
  }

  public void setCurrency(@javax.annotation.Nullable CurrencyOrNull currency) {
    this.currency = JsonNullable.<CurrencyOrNull>of(currency);
  }


  public CustomerObjectExtended email(@javax.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * The email of the customer
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }


  public CustomerObjectExtended legalName(@javax.annotation.Nullable String legalName) {
    
    this.legalName = legalName;
    return this;
  }

  /**
   * The legal company name of the customer
   * @return legalName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLegalName() {
    return legalName;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalName(@javax.annotation.Nullable String legalName) {
    this.legalName = legalName;
  }


  public CustomerObjectExtended legalNumber(@javax.annotation.Nullable String legalNumber) {
    
    this.legalNumber = legalNumber;
    return this;
  }

  /**
   * The legal company number of the customer
   * @return legalNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLegalNumber() {
    return legalNumber;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalNumber(@javax.annotation.Nullable String legalNumber) {
    this.legalNumber = legalNumber;
  }


  public CustomerObjectExtended logoUrl(@javax.annotation.Nullable String logoUrl) {
    
    this.logoUrl = logoUrl;
    return this;
  }

  /**
   * The logo URL of the customer
   * @return logoUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoUrl() {
    return logoUrl;
  }


  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoUrl(@javax.annotation.Nullable String logoUrl) {
    this.logoUrl = logoUrl;
  }


  public CustomerObjectExtended name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The full name of the customer
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CustomerObjectExtended firstname(@javax.annotation.Nullable String firstname) {
    
    this.firstname = firstname;
    return this;
  }

  /**
   * First name of the customer
   * @return firstname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstname() {
    return firstname;
  }


  @JsonProperty(JSON_PROPERTY_FIRSTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstname(@javax.annotation.Nullable String firstname) {
    this.firstname = firstname;
  }


  public CustomerObjectExtended lastname(@javax.annotation.Nullable String lastname) {
    
    this.lastname = lastname;
    return this;
  }

  /**
   * Last name of the customer
   * @return lastname
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LASTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastname() {
    return lastname;
  }


  @JsonProperty(JSON_PROPERTY_LASTNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastname(@javax.annotation.Nullable String lastname) {
    this.lastname = lastname;
  }


  public CustomerObjectExtended accountType(@javax.annotation.Nullable AccountTypeEnum accountType) {
    
    this.accountType = accountType;
    return this;
  }

  /**
   * The type of the account. It can have one of the following values: - &#x60;customer&#x60;: the account is a customer. - &#x60;partner&#x60;: the account is a partner.
   * @return accountType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountTypeEnum getAccountType() {
    return accountType;
  }


  @JsonProperty(JSON_PROPERTY_ACCOUNT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountType(@javax.annotation.Nullable AccountTypeEnum accountType) {
    this.accountType = accountType;
  }


  public CustomerObjectExtended customerType(@javax.annotation.Nullable CustomerTypeEnum customerType) {
    this.customerType = JsonNullable.<CustomerTypeEnum>of(customerType);
    
    return this;
  }

  /**
   * The type of the customer. It can have one of the following values: - &#x60;company&#x60;: the customer is a company. - &#x60;individual&#x60;: the customer is an individual.
   * @return customerType
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CustomerTypeEnum getCustomerType() {
        return customerType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CUSTOMER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CustomerTypeEnum> getCustomerType_JsonNullable() {
    return customerType;
  }
  
  @JsonProperty(JSON_PROPERTY_CUSTOMER_TYPE)
  public void setCustomerType_JsonNullable(JsonNullable<CustomerTypeEnum> customerType) {
    this.customerType = customerType;
  }

  public void setCustomerType(@javax.annotation.Nullable CustomerTypeEnum customerType) {
    this.customerType = JsonNullable.<CustomerTypeEnum>of(customerType);
  }


  public CustomerObjectExtended phone(@javax.annotation.Nullable String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * The phone number of the customer
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }


  public CustomerObjectExtended state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * The state of the customer&#39;s billing address
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }


  public CustomerObjectExtended taxIdentificationNumber(@javax.annotation.Nullable String taxIdentificationNumber) {
    
    this.taxIdentificationNumber = taxIdentificationNumber;
    return this;
  }

  /**
   * The tax identification number of the customer
   * @return taxIdentificationNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxIdentificationNumber() {
    return taxIdentificationNumber;
  }


  @JsonProperty(JSON_PROPERTY_TAX_IDENTIFICATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxIdentificationNumber(@javax.annotation.Nullable String taxIdentificationNumber) {
    this.taxIdentificationNumber = taxIdentificationNumber;
  }


  public CustomerObjectExtended timezone(@javax.annotation.Nullable TimezoneOrNull timezone) {
    this.timezone = JsonNullable.<TimezoneOrNull>of(timezone);
    
    return this;
  }

  /**
   * The customer&#39;s timezone, used for billing purposes in their local time. Overrides the organization&#39;s timezone
   * @return timezone
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public TimezoneOrNull getTimezone() {
        return timezone.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<TimezoneOrNull> getTimezone_JsonNullable() {
    return timezone;
  }
  
  @JsonProperty(JSON_PROPERTY_TIMEZONE)
  public void setTimezone_JsonNullable(JsonNullable<TimezoneOrNull> timezone) {
    this.timezone = timezone;
  }

  public void setTimezone(@javax.annotation.Nullable TimezoneOrNull timezone) {
    this.timezone = JsonNullable.<TimezoneOrNull>of(timezone);
  }


  public CustomerObjectExtended url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * The custom website URL of the customer
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public CustomerObjectExtended zipcode(@javax.annotation.Nullable String zipcode) {
    
    this.zipcode = zipcode;
    return this;
  }

  /**
   * The zipcode of the customer&#39;s billing address
   * @return zipcode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZipcode() {
    return zipcode;
  }


  @JsonProperty(JSON_PROPERTY_ZIPCODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZipcode(@javax.annotation.Nullable String zipcode) {
    this.zipcode = zipcode;
  }


  public CustomerObjectExtended netPaymentTerm(@javax.annotation.Nullable Integer netPaymentTerm) {
    
    this.netPaymentTerm = netPaymentTerm;
    return this;
  }

  /**
   * The net payment term, expressed in days, specifies the duration within which a customer is expected to remit payment after the invoice is finalized.
   * @return netPaymentTerm
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NET_PAYMENT_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNetPaymentTerm() {
    return netPaymentTerm;
  }


  @JsonProperty(JSON_PROPERTY_NET_PAYMENT_TERM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetPaymentTerm(@javax.annotation.Nullable Integer netPaymentTerm) {
    this.netPaymentTerm = netPaymentTerm;
  }


  public CustomerObjectExtended createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date of the customer creation, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC). The creation_date provides a standardized and internationally recognized timestamp for when the customer object was created
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public CustomerObjectExtended updatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The date of the customer update, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC). The update_date provides a standardized and internationally recognized timestamp for when the customer object was updated
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public CustomerObjectExtended finalizeZeroAmountInvoice(@javax.annotation.Nullable FinalizeZeroAmountInvoiceEnum finalizeZeroAmountInvoice) {
    
    this.finalizeZeroAmountInvoice = finalizeZeroAmountInvoice;
    return this;
  }

  /**
   * Specifies how invoices with a zero total amount should be handled: - &#x60;inherit&#x60;: (Default) Follows the organization-level configuration. - &#x60;finalize&#x60;: Invoices are issued and finalized even if the total amount is zero. - &#x60;skip&#x60;: Invoices with a total amount of zero are not finalized.
   * @return finalizeZeroAmountInvoice
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public FinalizeZeroAmountInvoiceEnum getFinalizeZeroAmountInvoice() {
    return finalizeZeroAmountInvoice;
  }


  @JsonProperty(JSON_PROPERTY_FINALIZE_ZERO_AMOUNT_INVOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinalizeZeroAmountInvoice(@javax.annotation.Nullable FinalizeZeroAmountInvoiceEnum finalizeZeroAmountInvoice) {
    this.finalizeZeroAmountInvoice = finalizeZeroAmountInvoice;
  }


  public CustomerObjectExtended skipInvoiceCustomSections(@javax.annotation.Nullable Boolean skipInvoiceCustomSections) {
    
    this.skipInvoiceCustomSections = skipInvoiceCustomSections;
    return this;
  }

  /**
   * Set to true to exclude all invoice custom sections from PDF generation for this customer only.
   * @return skipInvoiceCustomSections
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSkipInvoiceCustomSections() {
    return skipInvoiceCustomSections;
  }


  @JsonProperty(JSON_PROPERTY_SKIP_INVOICE_CUSTOM_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkipInvoiceCustomSections(@javax.annotation.Nullable Boolean skipInvoiceCustomSections) {
    this.skipInvoiceCustomSections = skipInvoiceCustomSections;
  }


  public CustomerObjectExtended billingConfiguration(@javax.annotation.Nullable CustomerBillingConfiguration billingConfiguration) {
    
    this.billingConfiguration = billingConfiguration;
    return this;
  }

  /**
   * Get billingConfiguration
   * @return billingConfiguration
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BILLING_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerBillingConfiguration getBillingConfiguration() {
    return billingConfiguration;
  }


  @JsonProperty(JSON_PROPERTY_BILLING_CONFIGURATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBillingConfiguration(@javax.annotation.Nullable CustomerBillingConfiguration billingConfiguration) {
    this.billingConfiguration = billingConfiguration;
  }


  public CustomerObjectExtended shippingAddress(@javax.annotation.Nullable Address shippingAddress) {
    
    this.shippingAddress = shippingAddress;
    return this;
  }

  /**
   * Get shippingAddress
   * @return shippingAddress
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Address getShippingAddress() {
    return shippingAddress;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShippingAddress(@javax.annotation.Nullable Address shippingAddress) {
    this.shippingAddress = shippingAddress;
  }


  public CustomerObjectExtended metadata(@javax.annotation.Nullable List<CustomerMetadata> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public CustomerObjectExtended addMetadataItem(CustomerMetadata metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CustomerMetadata> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable List<CustomerMetadata> metadata) {
    this.metadata = metadata;
  }


  public CustomerObjectExtended integrationCustomers(@javax.annotation.Nullable List<IntegrationCustomer> integrationCustomers) {
    
    this.integrationCustomers = integrationCustomers;
    return this;
  }

  public CustomerObjectExtended addIntegrationCustomersItem(IntegrationCustomer integrationCustomersItem) {
    if (this.integrationCustomers == null) {
      this.integrationCustomers = new ArrayList<>();
    }
    this.integrationCustomers.add(integrationCustomersItem);
    return this;
  }

  /**
   * Get integrationCustomers
   * @return integrationCustomers
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INTEGRATION_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IntegrationCustomer> getIntegrationCustomers() {
    return integrationCustomers;
  }


  @JsonProperty(JSON_PROPERTY_INTEGRATION_CUSTOMERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntegrationCustomers(@javax.annotation.Nullable List<IntegrationCustomer> integrationCustomers) {
    this.integrationCustomers = integrationCustomers;
  }


  public CustomerObjectExtended taxes(@javax.annotation.Nullable List<TaxObject> taxes) {
    
    this.taxes = taxes;
    return this;
  }

  public CustomerObjectExtended addTaxesItem(TaxObject taxesItem) {
    if (this.taxes == null) {
      this.taxes = new ArrayList<>();
    }
    this.taxes.add(taxesItem);
    return this;
  }

  /**
   * List of customer taxes
   * @return taxes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAXES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TaxObject> getTaxes() {
    return taxes;
  }


  @JsonProperty(JSON_PROPERTY_TAXES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxes(@javax.annotation.Nullable List<TaxObject> taxes) {
    this.taxes = taxes;
  }


  public CustomerObjectExtended applicableInvoiceCustomSections(@javax.annotation.Nullable List<InvoiceCustomSectionObject> applicableInvoiceCustomSections) {
    
    this.applicableInvoiceCustomSections = applicableInvoiceCustomSections;
    return this;
  }

  public CustomerObjectExtended addApplicableInvoiceCustomSectionsItem(InvoiceCustomSectionObject applicableInvoiceCustomSectionsItem) {
    if (this.applicableInvoiceCustomSections == null) {
      this.applicableInvoiceCustomSections = new ArrayList<>();
    }
    this.applicableInvoiceCustomSections.add(applicableInvoiceCustomSectionsItem);
    return this;
  }

  /**
   * The customer’s invoice custom section used for generating invoices.
   * @return applicableInvoiceCustomSections
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPLICABLE_INVOICE_CUSTOM_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<InvoiceCustomSectionObject> getApplicableInvoiceCustomSections() {
    return applicableInvoiceCustomSections;
  }


  @JsonProperty(JSON_PROPERTY_APPLICABLE_INVOICE_CUSTOM_SECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplicableInvoiceCustomSections(@javax.annotation.Nullable List<InvoiceCustomSectionObject> applicableInvoiceCustomSections) {
    this.applicableInvoiceCustomSections = applicableInvoiceCustomSections;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerObjectExtended customerObjectExtended = (CustomerObjectExtended) o;
    return Objects.equals(this.lagoId, customerObjectExtended.lagoId) &&
        Objects.equals(this.sequentialId, customerObjectExtended.sequentialId) &&
        Objects.equals(this.slug, customerObjectExtended.slug) &&
        Objects.equals(this.externalId, customerObjectExtended.externalId) &&
        Objects.equals(this.billingEntityCode, customerObjectExtended.billingEntityCode) &&
        Objects.equals(this.addressLine1, customerObjectExtended.addressLine1) &&
        Objects.equals(this.addressLine2, customerObjectExtended.addressLine2) &&
        Objects.equals(this.applicableTimezone, customerObjectExtended.applicableTimezone) &&
        Objects.equals(this.city, customerObjectExtended.city) &&
        equalsNullable(this.country, customerObjectExtended.country) &&
        equalsNullable(this.currency, customerObjectExtended.currency) &&
        Objects.equals(this.email, customerObjectExtended.email) &&
        Objects.equals(this.legalName, customerObjectExtended.legalName) &&
        Objects.equals(this.legalNumber, customerObjectExtended.legalNumber) &&
        Objects.equals(this.logoUrl, customerObjectExtended.logoUrl) &&
        Objects.equals(this.name, customerObjectExtended.name) &&
        Objects.equals(this.firstname, customerObjectExtended.firstname) &&
        Objects.equals(this.lastname, customerObjectExtended.lastname) &&
        Objects.equals(this.accountType, customerObjectExtended.accountType) &&
        equalsNullable(this.customerType, customerObjectExtended.customerType) &&
        Objects.equals(this.phone, customerObjectExtended.phone) &&
        Objects.equals(this.state, customerObjectExtended.state) &&
        Objects.equals(this.taxIdentificationNumber, customerObjectExtended.taxIdentificationNumber) &&
        equalsNullable(this.timezone, customerObjectExtended.timezone) &&
        Objects.equals(this.url, customerObjectExtended.url) &&
        Objects.equals(this.zipcode, customerObjectExtended.zipcode) &&
        Objects.equals(this.netPaymentTerm, customerObjectExtended.netPaymentTerm) &&
        Objects.equals(this.createdAt, customerObjectExtended.createdAt) &&
        Objects.equals(this.updatedAt, customerObjectExtended.updatedAt) &&
        Objects.equals(this.finalizeZeroAmountInvoice, customerObjectExtended.finalizeZeroAmountInvoice) &&
        Objects.equals(this.skipInvoiceCustomSections, customerObjectExtended.skipInvoiceCustomSections) &&
        Objects.equals(this.billingConfiguration, customerObjectExtended.billingConfiguration) &&
        Objects.equals(this.shippingAddress, customerObjectExtended.shippingAddress) &&
        Objects.equals(this.metadata, customerObjectExtended.metadata) &&
        Objects.equals(this.integrationCustomers, customerObjectExtended.integrationCustomers) &&
        Objects.equals(this.taxes, customerObjectExtended.taxes) &&
        Objects.equals(this.applicableInvoiceCustomSections, customerObjectExtended.applicableInvoiceCustomSections);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(lagoId, sequentialId, slug, externalId, billingEntityCode, addressLine1, addressLine2, applicableTimezone, city, hashCodeNullable(country), hashCodeNullable(currency), email, legalName, legalNumber, logoUrl, name, firstname, lastname, accountType, hashCodeNullable(customerType), phone, state, taxIdentificationNumber, hashCodeNullable(timezone), url, zipcode, netPaymentTerm, createdAt, updatedAt, finalizeZeroAmountInvoice, skipInvoiceCustomSections, billingConfiguration, shippingAddress, metadata, integrationCustomers, taxes, applicableInvoiceCustomSections);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerObjectExtended {\n");
    sb.append("    lagoId: ").append(toIndentedString(lagoId)).append("\n");
    sb.append("    sequentialId: ").append(toIndentedString(sequentialId)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    billingEntityCode: ").append(toIndentedString(billingEntityCode)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    applicableTimezone: ").append(toIndentedString(applicableTimezone)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    legalNumber: ").append(toIndentedString(legalNumber)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    customerType: ").append(toIndentedString(customerType)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    taxIdentificationNumber: ").append(toIndentedString(taxIdentificationNumber)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    zipcode: ").append(toIndentedString(zipcode)).append("\n");
    sb.append("    netPaymentTerm: ").append(toIndentedString(netPaymentTerm)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    finalizeZeroAmountInvoice: ").append(toIndentedString(finalizeZeroAmountInvoice)).append("\n");
    sb.append("    skipInvoiceCustomSections: ").append(toIndentedString(skipInvoiceCustomSections)).append("\n");
    sb.append("    billingConfiguration: ").append(toIndentedString(billingConfiguration)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    integrationCustomers: ").append(toIndentedString(integrationCustomers)).append("\n");
    sb.append("    taxes: ").append(toIndentedString(taxes)).append("\n");
    sb.append("    applicableInvoiceCustomSections: ").append(toIndentedString(applicableInvoiceCustomSections)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

