/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ErrorDetailObject
 */
@JsonPropertyOrder({
  ErrorDetailObject.JSON_PROPERTY_LAGO_ID,
  ErrorDetailObject.JSON_PROPERTY_ERROR_CODE,
  ErrorDetailObject.JSON_PROPERTY_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class ErrorDetailObject {
  public static final String JSON_PROPERTY_LAGO_ID = "lago_id";
  @javax.annotation.Nullable
  private UUID lagoId;

  public static final String JSON_PROPERTY_ERROR_CODE = "error_code";
  @javax.annotation.Nonnull
  private String errorCode;

  public static final String JSON_PROPERTY_DETAILS = "details";
  @javax.annotation.Nonnull
  private Object details;

  public ErrorDetailObject() {
  }

  public ErrorDetailObject lagoId(@javax.annotation.Nullable UUID lagoId) {
    
    this.lagoId = lagoId;
    return this;
  }

  /**
   * Unique identifier assigned to the error_detail within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the error&#39;s record within the Lago system.
   * @return lagoId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoId() {
    return lagoId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoId(@javax.annotation.Nullable UUID lagoId) {
    this.lagoId = lagoId;
  }


  public ErrorDetailObject errorCode(@javax.annotation.Nonnull String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Code that specifies part of the application / connection, where the error originally happened
   * @return errorCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrorCode(@javax.annotation.Nonnull String errorCode) {
    this.errorCode = errorCode;
  }


  public ErrorDetailObject details(@javax.annotation.Nonnull Object details) {
    
    this.details = details;
    return this;
  }

  /**
   * Key value list of more elaborated error detail, where by the key of error_code an external service error details are stored
   * @return details
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getDetails() {
    return details;
  }


  @JsonProperty(JSON_PROPERTY_DETAILS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDetails(@javax.annotation.Nonnull Object details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorDetailObject errorDetailObject = (ErrorDetailObject) o;
    return Objects.equals(this.lagoId, errorDetailObject.lagoId) &&
        Objects.equals(this.errorCode, errorDetailObject.errorCode) &&
        Objects.equals(this.details, errorDetailObject.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lagoId, errorCode, details);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorDetailObject {\n");
    sb.append("    lagoId: ").append(toIndentedString(lagoId)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

