/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.BillableMetricEvaluateExpressionInputEventPropertiesValue;
import org.openapitools.client.model.EventInputObjectTimestamp;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EventInputObject
 */
@JsonPropertyOrder({
  EventInputObject.JSON_PROPERTY_TRANSACTION_ID,
  EventInputObject.JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID,
  EventInputObject.JSON_PROPERTY_CODE,
  EventInputObject.JSON_PROPERTY_TIMESTAMP,
  EventInputObject.JSON_PROPERTY_PRECISE_TOTAL_AMOUNT_CENTS,
  EventInputObject.JSON_PROPERTY_PROPERTIES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class EventInputObject {
  public static final String JSON_PROPERTY_TRANSACTION_ID = "transaction_id";
  @javax.annotation.Nonnull
  private String transactionId;

  public static final String JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID = "external_subscription_id";
  @javax.annotation.Nonnull
  private String externalSubscriptionId;

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @javax.annotation.Nullable
  private EventInputObjectTimestamp timestamp;

  public static final String JSON_PROPERTY_PRECISE_TOTAL_AMOUNT_CENTS = "precise_total_amount_cents";
  private JsonNullable<String> preciseTotalAmountCents = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROPERTIES = "properties";
  @javax.annotation.Nullable
  private Map<String, BillableMetricEvaluateExpressionInputEventPropertiesValue> properties = new HashMap<>();

  public EventInputObject() {
  }

  public EventInputObject transactionId(@javax.annotation.Nonnull String transactionId) {
    
    this.transactionId = transactionId;
    return this;
  }

  /**
   * This field represents a unique identifier for the event. It is crucial for ensuring idempotency, meaning that each event can be uniquely identified and processed without causing any unintended side effects.  WARNING: If the Lago organization is configured to use the new Clickhouse-based event pipeline (designed for high-volume processing), the idempotency logic is handled differently. Event uniqueness is maintained with both &#x60;transaction_id&#x60; and &#x60;timestamp&#x60; fields. If a new event arrives with identical values for these two fields as an existing event, the new one will overwrite the previous event rather than being rejected. 
   * @return transactionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionId() {
    return transactionId;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public EventInputObject externalSubscriptionId(@javax.annotation.Nonnull String externalSubscriptionId) {
    
    this.externalSubscriptionId = externalSubscriptionId;
    return this;
  }

  /**
   * The unique identifier of the subscription in your application. This field is mandatory in order to link events to the correct customer subscription.
   * @return externalSubscriptionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalSubscriptionId() {
    return externalSubscriptionId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalSubscriptionId(@javax.annotation.Nonnull String externalSubscriptionId) {
    this.externalSubscriptionId = externalSubscriptionId;
  }


  public EventInputObject code(@javax.annotation.Nonnull String code) {
    
    this.code = code;
    return this;
  }

  /**
   * The code that identifies a targeted billable metric. It is essential that this code matches the &#x60;code&#x60; property of one of your active billable metrics. If the provided code does not correspond to any active billable metric, it will be ignored during the process.
   * @return code
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }


  public EventInputObject timestamp(@javax.annotation.Nullable EventInputObjectTimestamp timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Get timestamp
   * @return timestamp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventInputObjectTimestamp getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@javax.annotation.Nullable EventInputObjectTimestamp timestamp) {
    this.timestamp = timestamp;
  }


  public EventInputObject preciseTotalAmountCents(@javax.annotation.Nullable String preciseTotalAmountCents) {
    this.preciseTotalAmountCents = JsonNullable.<String>of(preciseTotalAmountCents);
    
    return this;
  }

  /**
   * The precise total amount in cents with precision used by the &#x60;dynamic&#x60; pricing model to compute the usage amount.
   * @return preciseTotalAmountCents
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getPreciseTotalAmountCents() {
        return preciseTotalAmountCents.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PRECISE_TOTAL_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPreciseTotalAmountCents_JsonNullable() {
    return preciseTotalAmountCents;
  }
  
  @JsonProperty(JSON_PROPERTY_PRECISE_TOTAL_AMOUNT_CENTS)
  public void setPreciseTotalAmountCents_JsonNullable(JsonNullable<String> preciseTotalAmountCents) {
    this.preciseTotalAmountCents = preciseTotalAmountCents;
  }

  public void setPreciseTotalAmountCents(@javax.annotation.Nullable String preciseTotalAmountCents) {
    this.preciseTotalAmountCents = JsonNullable.<String>of(preciseTotalAmountCents);
  }


  public EventInputObject properties(@javax.annotation.Nullable Map<String, BillableMetricEvaluateExpressionInputEventPropertiesValue> properties) {
    
    this.properties = properties;
    return this;
  }

  public EventInputObject putPropertiesItem(String key, BillableMetricEvaluateExpressionInputEventPropertiesValue propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

  /**
   * This field represents additional properties associated with the event, which are utilized in the calculation of the final fee. This object becomes mandatory when the targeted billable metric employs a &#x60;sum_agg&#x60;, &#x60;max_agg&#x60;, or &#x60;unique_count_agg&#x60; aggregation method. However, when using a simple &#x60;count_agg&#x60;, this object is not required.
   * @return properties
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, BillableMetricEvaluateExpressionInputEventPropertiesValue> getProperties() {
    return properties;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProperties(@javax.annotation.Nullable Map<String, BillableMetricEvaluateExpressionInputEventPropertiesValue> properties) {
    this.properties = properties;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventInputObject eventInputObject = (EventInputObject) o;
    return Objects.equals(this.transactionId, eventInputObject.transactionId) &&
        Objects.equals(this.externalSubscriptionId, eventInputObject.externalSubscriptionId) &&
        Objects.equals(this.code, eventInputObject.code) &&
        Objects.equals(this.timestamp, eventInputObject.timestamp) &&
        equalsNullable(this.preciseTotalAmountCents, eventInputObject.preciseTotalAmountCents) &&
        Objects.equals(this.properties, eventInputObject.properties);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(transactionId, externalSubscriptionId, code, timestamp, hashCodeNullable(preciseTotalAmountCents), properties);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventInputObject {\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    externalSubscriptionId: ").append(toIndentedString(externalSubscriptionId)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    preciseTotalAmountCents: ").append(toIndentedString(preciseTotalAmountCents)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

