/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EventsErrorsObject
 */
@JsonPropertyOrder({
  EventsErrorsObject.JSON_PROPERTY_INVALID_CODE,
  EventsErrorsObject.JSON_PROPERTY_MISSING_AGGREGATION_PROPERTY,
  EventsErrorsObject.JSON_PROPERTY_INVALID_FILTER_VALUES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class EventsErrorsObject {
  public static final String JSON_PROPERTY_INVALID_CODE = "invalid_code";
  @javax.annotation.Nonnull
  private List<String> invalidCode = new ArrayList<>();

  public static final String JSON_PROPERTY_MISSING_AGGREGATION_PROPERTY = "missing_aggregation_property";
  @javax.annotation.Nonnull
  private List<String> missingAggregationProperty = new ArrayList<>();

  public static final String JSON_PROPERTY_INVALID_FILTER_VALUES = "invalid_filter_values";
  @javax.annotation.Nonnull
  private List<String> invalidFilterValues = new ArrayList<>();

  public EventsErrorsObject() {
  }

  public EventsErrorsObject invalidCode(@javax.annotation.Nonnull List<String> invalidCode) {
    
    this.invalidCode = invalidCode;
    return this;
  }

  public EventsErrorsObject addInvalidCodeItem(String invalidCodeItem) {
    if (this.invalidCode == null) {
      this.invalidCode = new ArrayList<>();
    }
    this.invalidCode.add(invalidCodeItem);
    return this;
  }

  /**
   * List of event transaction_id with an invalid code
   * @return invalidCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVALID_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getInvalidCode() {
    return invalidCode;
  }


  @JsonProperty(JSON_PROPERTY_INVALID_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInvalidCode(@javax.annotation.Nonnull List<String> invalidCode) {
    this.invalidCode = invalidCode;
  }


  public EventsErrorsObject missingAggregationProperty(@javax.annotation.Nonnull List<String> missingAggregationProperty) {
    
    this.missingAggregationProperty = missingAggregationProperty;
    return this;
  }

  public EventsErrorsObject addMissingAggregationPropertyItem(String missingAggregationPropertyItem) {
    if (this.missingAggregationProperty == null) {
      this.missingAggregationProperty = new ArrayList<>();
    }
    this.missingAggregationProperty.add(missingAggregationPropertyItem);
    return this;
  }

  /**
   * List of event transaction_id with a missing aggregation property
   * @return missingAggregationProperty
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MISSING_AGGREGATION_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMissingAggregationProperty() {
    return missingAggregationProperty;
  }


  @JsonProperty(JSON_PROPERTY_MISSING_AGGREGATION_PROPERTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMissingAggregationProperty(@javax.annotation.Nonnull List<String> missingAggregationProperty) {
    this.missingAggregationProperty = missingAggregationProperty;
  }


  public EventsErrorsObject invalidFilterValues(@javax.annotation.Nonnull List<String> invalidFilterValues) {
    
    this.invalidFilterValues = invalidFilterValues;
    return this;
  }

  public EventsErrorsObject addInvalidFilterValuesItem(String invalidFilterValuesItem) {
    if (this.invalidFilterValues == null) {
      this.invalidFilterValues = new ArrayList<>();
    }
    this.invalidFilterValues.add(invalidFilterValuesItem);
    return this;
  }

  /**
   * List of event transaction_id with invalid filter values
   * @return invalidFilterValues
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVALID_FILTER_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getInvalidFilterValues() {
    return invalidFilterValues;
  }


  @JsonProperty(JSON_PROPERTY_INVALID_FILTER_VALUES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInvalidFilterValues(@javax.annotation.Nonnull List<String> invalidFilterValues) {
    this.invalidFilterValues = invalidFilterValues;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventsErrorsObject eventsErrorsObject = (EventsErrorsObject) o;
    return Objects.equals(this.invalidCode, eventsErrorsObject.invalidCode) &&
        Objects.equals(this.missingAggregationProperty, eventsErrorsObject.missingAggregationProperty) &&
        Objects.equals(this.invalidFilterValues, eventsErrorsObject.invalidFilterValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invalidCode, missingAggregationProperty, invalidFilterValues);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventsErrorsObject {\n");
    sb.append("    invalidCode: ").append(toIndentedString(invalidCode)).append("\n");
    sb.append("    missingAggregationProperty: ").append(toIndentedString(missingAggregationProperty)).append("\n");
    sb.append("    invalidFilterValues: ").append(toIndentedString(invalidFilterValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

