/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.FeeAmountDetailsGraduatedPercentageRangesInner;
import org.openapitools.client.model.FeeAmountDetailsGraduatedRangesInner;
import org.openapitools.client.model.FeeAmountDetailsVolumeRangesInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FeeAmountDetails
 */
@JsonPropertyOrder({
  FeeAmountDetails.JSON_PROPERTY_GRADUATED_RANGES,
  FeeAmountDetails.JSON_PROPERTY_GRADUATED_PERCENTAGE_RANGES,
  FeeAmountDetails.JSON_PROPERTY_FREE_UNITS,
  FeeAmountDetails.JSON_PROPERTY_PAID_UNITS,
  FeeAmountDetails.JSON_PROPERTY_PER_PACKAGE_SIZE,
  FeeAmountDetails.JSON_PROPERTY_PER_PACKAGE_UNIT_AMOUNT,
  FeeAmountDetails.JSON_PROPERTY_UNITS,
  FeeAmountDetails.JSON_PROPERTY_FREE_EVENTS,
  FeeAmountDetails.JSON_PROPERTY_RATE,
  FeeAmountDetails.JSON_PROPERTY_PER_UNIT_TOTAL_AMOUNT,
  FeeAmountDetails.JSON_PROPERTY_PAID_EVENTS,
  FeeAmountDetails.JSON_PROPERTY_FIXED_FEE_UNIT_AMOUNT,
  FeeAmountDetails.JSON_PROPERTY_FIXED_FEE_TOTAL_AMOUNT,
  FeeAmountDetails.JSON_PROPERTY_MIN_MAX_ADJUSTMENT_TOTAL_AMOUNT,
  FeeAmountDetails.JSON_PROPERTY_VOLUME_RANGES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class FeeAmountDetails {
  public static final String JSON_PROPERTY_GRADUATED_RANGES = "graduated_ranges";
  @javax.annotation.Nullable
  private List<FeeAmountDetailsGraduatedRangesInner> graduatedRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_GRADUATED_PERCENTAGE_RANGES = "graduated_percentage_ranges";
  @javax.annotation.Nullable
  private List<FeeAmountDetailsGraduatedPercentageRangesInner> graduatedPercentageRanges = new ArrayList<>();

  public static final String JSON_PROPERTY_FREE_UNITS = "free_units";
  @javax.annotation.Nullable
  private String freeUnits;

  public static final String JSON_PROPERTY_PAID_UNITS = "paid_units";
  @javax.annotation.Nullable
  private String paidUnits;

  public static final String JSON_PROPERTY_PER_PACKAGE_SIZE = "per_package_size";
  @javax.annotation.Nullable
  private Integer perPackageSize;

  public static final String JSON_PROPERTY_PER_PACKAGE_UNIT_AMOUNT = "per_package_unit_amount";
  @javax.annotation.Nullable
  private String perPackageUnitAmount;

  public static final String JSON_PROPERTY_UNITS = "units";
  @javax.annotation.Nullable
  private String units;

  public static final String JSON_PROPERTY_FREE_EVENTS = "free_events";
  @javax.annotation.Nullable
  private Integer freeEvents;

  public static final String JSON_PROPERTY_RATE = "rate";
  @javax.annotation.Nullable
  private String rate;

  public static final String JSON_PROPERTY_PER_UNIT_TOTAL_AMOUNT = "per_unit_total_amount";
  @javax.annotation.Nullable
  private String perUnitTotalAmount;

  public static final String JSON_PROPERTY_PAID_EVENTS = "paid_events";
  @javax.annotation.Nullable
  private Integer paidEvents;

  public static final String JSON_PROPERTY_FIXED_FEE_UNIT_AMOUNT = "fixed_fee_unit_amount";
  @javax.annotation.Nullable
  private String fixedFeeUnitAmount;

  public static final String JSON_PROPERTY_FIXED_FEE_TOTAL_AMOUNT = "fixed_fee_total_amount";
  @javax.annotation.Nullable
  private String fixedFeeTotalAmount;

  public static final String JSON_PROPERTY_MIN_MAX_ADJUSTMENT_TOTAL_AMOUNT = "min_max_adjustment_total_amount";
  @javax.annotation.Nullable
  private String minMaxAdjustmentTotalAmount;

  public static final String JSON_PROPERTY_VOLUME_RANGES = "volume_ranges";
  @javax.annotation.Nullable
  private List<FeeAmountDetailsVolumeRangesInner> volumeRanges = new ArrayList<>();

  public FeeAmountDetails() {
  }

  public FeeAmountDetails graduatedRanges(@javax.annotation.Nullable List<FeeAmountDetailsGraduatedRangesInner> graduatedRanges) {
    
    this.graduatedRanges = graduatedRanges;
    return this;
  }

  public FeeAmountDetails addGraduatedRangesItem(FeeAmountDetailsGraduatedRangesInner graduatedRangesItem) {
    if (this.graduatedRanges == null) {
      this.graduatedRanges = new ArrayList<>();
    }
    this.graduatedRanges.add(graduatedRangesItem);
    return this;
  }

  /**
   * Graduated ranges, used for a &#x60;graduated&#x60; charge model.
   * @return graduatedRanges
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRADUATED_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FeeAmountDetailsGraduatedRangesInner> getGraduatedRanges() {
    return graduatedRanges;
  }


  @JsonProperty(JSON_PROPERTY_GRADUATED_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGraduatedRanges(@javax.annotation.Nullable List<FeeAmountDetailsGraduatedRangesInner> graduatedRanges) {
    this.graduatedRanges = graduatedRanges;
  }


  public FeeAmountDetails graduatedPercentageRanges(@javax.annotation.Nullable List<FeeAmountDetailsGraduatedPercentageRangesInner> graduatedPercentageRanges) {
    
    this.graduatedPercentageRanges = graduatedPercentageRanges;
    return this;
  }

  public FeeAmountDetails addGraduatedPercentageRangesItem(FeeAmountDetailsGraduatedPercentageRangesInner graduatedPercentageRangesItem) {
    if (this.graduatedPercentageRanges == null) {
      this.graduatedPercentageRanges = new ArrayList<>();
    }
    this.graduatedPercentageRanges.add(graduatedPercentageRangesItem);
    return this;
  }

  /**
   * Graduated percentage ranges, used for a &#x60;graduated_percentage&#x60; charge model.
   * @return graduatedPercentageRanges
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GRADUATED_PERCENTAGE_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FeeAmountDetailsGraduatedPercentageRangesInner> getGraduatedPercentageRanges() {
    return graduatedPercentageRanges;
  }


  @JsonProperty(JSON_PROPERTY_GRADUATED_PERCENTAGE_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGraduatedPercentageRanges(@javax.annotation.Nullable List<FeeAmountDetailsGraduatedPercentageRangesInner> graduatedPercentageRanges) {
    this.graduatedPercentageRanges = graduatedPercentageRanges;
  }


  public FeeAmountDetails freeUnits(@javax.annotation.Nullable String freeUnits) {
    
    this.freeUnits = freeUnits;
    return this;
  }

  /**
   * The quantity of units that are provided free of charge for each billing period in a &#x60;package&#x60; charge model.
   * @return freeUnits
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FREE_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFreeUnits() {
    return freeUnits;
  }


  @JsonProperty(JSON_PROPERTY_FREE_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFreeUnits(@javax.annotation.Nullable String freeUnits) {
    this.freeUnits = freeUnits;
  }


  public FeeAmountDetails paidUnits(@javax.annotation.Nullable String paidUnits) {
    
    this.paidUnits = paidUnits;
    return this;
  }

  /**
   * The quantity of units that are not provided free of charge for each billing period in a &#x60;package&#x60; charge model.
   * @return paidUnits
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAID_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaidUnits() {
    return paidUnits;
  }


  @JsonProperty(JSON_PROPERTY_PAID_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaidUnits(@javax.annotation.Nullable String paidUnits) {
    this.paidUnits = paidUnits;
  }


  public FeeAmountDetails perPackageSize(@javax.annotation.Nullable Integer perPackageSize) {
    
    this.perPackageSize = perPackageSize;
    return this;
  }

  /**
   * The quantity of units included, defined for Package or Percentage charge model.
   * @return perPackageSize
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PER_PACKAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPerPackageSize() {
    return perPackageSize;
  }


  @JsonProperty(JSON_PROPERTY_PER_PACKAGE_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerPackageSize(@javax.annotation.Nullable Integer perPackageSize) {
    this.perPackageSize = perPackageSize;
  }


  public FeeAmountDetails perPackageUnitAmount(@javax.annotation.Nullable String perPackageUnitAmount) {
    
    this.perPackageUnitAmount = perPackageUnitAmount;
    return this;
  }

  /**
   * Total amount to charge for received paid_units, defined for Package or Percentage charge model.
   * @return perPackageUnitAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PER_PACKAGE_UNIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPerPackageUnitAmount() {
    return perPackageUnitAmount;
  }


  @JsonProperty(JSON_PROPERTY_PER_PACKAGE_UNIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerPackageUnitAmount(@javax.annotation.Nullable String perPackageUnitAmount) {
    this.perPackageUnitAmount = perPackageUnitAmount;
  }


  public FeeAmountDetails units(@javax.annotation.Nullable String units) {
    
    this.units = units;
    return this;
  }

  /**
   * The total units received in Lago for the Percentage charge model.
   * @return units
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnits() {
    return units;
  }


  @JsonProperty(JSON_PROPERTY_UNITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnits(@javax.annotation.Nullable String units) {
    this.units = units;
  }


  public FeeAmountDetails freeEvents(@javax.annotation.Nullable Integer freeEvents) {
    
    this.freeEvents = freeEvents;
    return this;
  }

  /**
   * Total number of free events allowed for the Percentage charge model.
   * @return freeEvents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FREE_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFreeEvents() {
    return freeEvents;
  }


  @JsonProperty(JSON_PROPERTY_FREE_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFreeEvents(@javax.annotation.Nullable Integer freeEvents) {
    this.freeEvents = freeEvents;
  }


  public FeeAmountDetails rate(@javax.annotation.Nullable String rate) {
    
    this.rate = rate;
    return this;
  }

  /**
   * Percentage rate applied for the Percentage charge model.
   * @return rate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRate() {
    return rate;
  }


  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRate(@javax.annotation.Nullable String rate) {
    this.rate = rate;
  }


  public FeeAmountDetails perUnitTotalAmount(@javax.annotation.Nullable String perUnitTotalAmount) {
    
    this.perUnitTotalAmount = perUnitTotalAmount;
    return this;
  }

  /**
   * Total amount of received units to be charged for the Percentage charge model.
   * @return perUnitTotalAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PER_UNIT_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPerUnitTotalAmount() {
    return perUnitTotalAmount;
  }


  @JsonProperty(JSON_PROPERTY_PER_UNIT_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPerUnitTotalAmount(@javax.annotation.Nullable String perUnitTotalAmount) {
    this.perUnitTotalAmount = perUnitTotalAmount;
  }


  public FeeAmountDetails paidEvents(@javax.annotation.Nullable Integer paidEvents) {
    
    this.paidEvents = paidEvents;
    return this;
  }

  /**
   * Total number of paid events for the Percentage charge model.
   * @return paidEvents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAID_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPaidEvents() {
    return paidEvents;
  }


  @JsonProperty(JSON_PROPERTY_PAID_EVENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaidEvents(@javax.annotation.Nullable Integer paidEvents) {
    this.paidEvents = paidEvents;
  }


  public FeeAmountDetails fixedFeeUnitAmount(@javax.annotation.Nullable String fixedFeeUnitAmount) {
    
    this.fixedFeeUnitAmount = fixedFeeUnitAmount;
    return this;
  }

  /**
   * Fixed fee unit price per received paid_event for the Percentage charge model.
   * @return fixedFeeUnitAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIXED_FEE_UNIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFixedFeeUnitAmount() {
    return fixedFeeUnitAmount;
  }


  @JsonProperty(JSON_PROPERTY_FIXED_FEE_UNIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFixedFeeUnitAmount(@javax.annotation.Nullable String fixedFeeUnitAmount) {
    this.fixedFeeUnitAmount = fixedFeeUnitAmount;
  }


  public FeeAmountDetails fixedFeeTotalAmount(@javax.annotation.Nullable String fixedFeeTotalAmount) {
    
    this.fixedFeeTotalAmount = fixedFeeTotalAmount;
    return this;
  }

  /**
   * Total amount to charge for received paid_events for the Percentage charge model.
   * @return fixedFeeTotalAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIXED_FEE_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFixedFeeTotalAmount() {
    return fixedFeeTotalAmount;
  }


  @JsonProperty(JSON_PROPERTY_FIXED_FEE_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFixedFeeTotalAmount(@javax.annotation.Nullable String fixedFeeTotalAmount) {
    this.fixedFeeTotalAmount = fixedFeeTotalAmount;
  }


  public FeeAmountDetails minMaxAdjustmentTotalAmount(@javax.annotation.Nullable String minMaxAdjustmentTotalAmount) {
    
    this.minMaxAdjustmentTotalAmount = minMaxAdjustmentTotalAmount;
    return this;
  }

  /**
   * Total adjustment amount linked to minimum and maximum spending per transaction for the Percentage charge model.
   * @return minMaxAdjustmentTotalAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIN_MAX_ADJUSTMENT_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMinMaxAdjustmentTotalAmount() {
    return minMaxAdjustmentTotalAmount;
  }


  @JsonProperty(JSON_PROPERTY_MIN_MAX_ADJUSTMENT_TOTAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinMaxAdjustmentTotalAmount(@javax.annotation.Nullable String minMaxAdjustmentTotalAmount) {
    this.minMaxAdjustmentTotalAmount = minMaxAdjustmentTotalAmount;
  }


  public FeeAmountDetails volumeRanges(@javax.annotation.Nullable List<FeeAmountDetailsVolumeRangesInner> volumeRanges) {
    
    this.volumeRanges = volumeRanges;
    return this;
  }

  public FeeAmountDetails addVolumeRangesItem(FeeAmountDetailsVolumeRangesInner volumeRangesItem) {
    if (this.volumeRanges == null) {
      this.volumeRanges = new ArrayList<>();
    }
    this.volumeRanges.add(volumeRangesItem);
    return this;
  }

  /**
   * Volume ranges, used for a &#x60;volume&#x60; charge model.
   * @return volumeRanges
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VOLUME_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FeeAmountDetailsVolumeRangesInner> getVolumeRanges() {
    return volumeRanges;
  }


  @JsonProperty(JSON_PROPERTY_VOLUME_RANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVolumeRanges(@javax.annotation.Nullable List<FeeAmountDetailsVolumeRangesInner> volumeRanges) {
    this.volumeRanges = volumeRanges;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeAmountDetails feeAmountDetails = (FeeAmountDetails) o;
    return Objects.equals(this.graduatedRanges, feeAmountDetails.graduatedRanges) &&
        Objects.equals(this.graduatedPercentageRanges, feeAmountDetails.graduatedPercentageRanges) &&
        Objects.equals(this.freeUnits, feeAmountDetails.freeUnits) &&
        Objects.equals(this.paidUnits, feeAmountDetails.paidUnits) &&
        Objects.equals(this.perPackageSize, feeAmountDetails.perPackageSize) &&
        Objects.equals(this.perPackageUnitAmount, feeAmountDetails.perPackageUnitAmount) &&
        Objects.equals(this.units, feeAmountDetails.units) &&
        Objects.equals(this.freeEvents, feeAmountDetails.freeEvents) &&
        Objects.equals(this.rate, feeAmountDetails.rate) &&
        Objects.equals(this.perUnitTotalAmount, feeAmountDetails.perUnitTotalAmount) &&
        Objects.equals(this.paidEvents, feeAmountDetails.paidEvents) &&
        Objects.equals(this.fixedFeeUnitAmount, feeAmountDetails.fixedFeeUnitAmount) &&
        Objects.equals(this.fixedFeeTotalAmount, feeAmountDetails.fixedFeeTotalAmount) &&
        Objects.equals(this.minMaxAdjustmentTotalAmount, feeAmountDetails.minMaxAdjustmentTotalAmount) &&
        Objects.equals(this.volumeRanges, feeAmountDetails.volumeRanges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(graduatedRanges, graduatedPercentageRanges, freeUnits, paidUnits, perPackageSize, perPackageUnitAmount, units, freeEvents, rate, perUnitTotalAmount, paidEvents, fixedFeeUnitAmount, fixedFeeTotalAmount, minMaxAdjustmentTotalAmount, volumeRanges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeAmountDetails {\n");
    sb.append("    graduatedRanges: ").append(toIndentedString(graduatedRanges)).append("\n");
    sb.append("    graduatedPercentageRanges: ").append(toIndentedString(graduatedPercentageRanges)).append("\n");
    sb.append("    freeUnits: ").append(toIndentedString(freeUnits)).append("\n");
    sb.append("    paidUnits: ").append(toIndentedString(paidUnits)).append("\n");
    sb.append("    perPackageSize: ").append(toIndentedString(perPackageSize)).append("\n");
    sb.append("    perPackageUnitAmount: ").append(toIndentedString(perPackageUnitAmount)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    freeEvents: ").append(toIndentedString(freeEvents)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    perUnitTotalAmount: ").append(toIndentedString(perUnitTotalAmount)).append("\n");
    sb.append("    paidEvents: ").append(toIndentedString(paidEvents)).append("\n");
    sb.append("    fixedFeeUnitAmount: ").append(toIndentedString(fixedFeeUnitAmount)).append("\n");
    sb.append("    fixedFeeTotalAmount: ").append(toIndentedString(fixedFeeTotalAmount)).append("\n");
    sb.append("    minMaxAdjustmentTotalAmount: ").append(toIndentedString(minMaxAdjustmentTotalAmount)).append("\n");
    sb.append("    volumeRanges: ").append(toIndentedString(volumeRanges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

