/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Item attached to the fee
 */
@JsonPropertyOrder({
  FeeObjectItem.JSON_PROPERTY_TYPE,
  FeeObjectItem.JSON_PROPERTY_CODE,
  FeeObjectItem.JSON_PROPERTY_NAME,
  FeeObjectItem.JSON_PROPERTY_INVOICE_DISPLAY_NAME,
  FeeObjectItem.JSON_PROPERTY_FILTER_INVOICE_DISPLAY_NAME,
  FeeObjectItem.JSON_PROPERTY_FILTERS,
  FeeObjectItem.JSON_PROPERTY_LAGO_ITEM_ID,
  FeeObjectItem.JSON_PROPERTY_ITEM_TYPE,
  FeeObjectItem.JSON_PROPERTY_GROUPED_BY
})
@JsonTypeName("FeeObject_item")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class FeeObjectItem {
  /**
   * The fee type. Possible values are &#x60;add-on&#x60;, &#x60;charge&#x60;, &#x60;credit&#x60;, &#x60;subscription&#x60; or &#x60;commitment&#x60;.
   */
  public enum TypeEnum {
    CHARGE(String.valueOf("charge")),
    
    ADD_ON(String.valueOf("add_on")),
    
    SUBSCRIPTION(String.valueOf("subscription")),
    
    CREDIT(String.valueOf("credit"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private TypeEnum type;

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_INVOICE_DISPLAY_NAME = "invoice_display_name";
  @javax.annotation.Nullable
  private String invoiceDisplayName;

  public static final String JSON_PROPERTY_FILTER_INVOICE_DISPLAY_NAME = "filter_invoice_display_name";
  @javax.annotation.Nullable
  private String filterInvoiceDisplayName;

  public static final String JSON_PROPERTY_FILTERS = "filters";
  @javax.annotation.Nullable
  private Map<String, List<String>> filters = new HashMap<>();

  public static final String JSON_PROPERTY_LAGO_ITEM_ID = "lago_item_id";
  @javax.annotation.Nonnull
  private UUID lagoItemId;

  /**
   * The type of the fee item. Possible values are &#x60;AddOn&#x60;, &#x60;BillableMetric&#x60;, &#x60;WalletTransaction&#x60;, &#x60;Subscription&#x60; or &#x60;Commitment&#x60;.
   */
  public enum ItemTypeEnum {
    ADD_ON(String.valueOf("AddOn")),
    
    BILLABLE_METRIC(String.valueOf("BillableMetric")),
    
    SUBSCRIPTION(String.valueOf("Subscription")),
    
    WALLET_TRANSACTION(String.valueOf("WalletTransaction"));

    private String value;

    ItemTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ItemTypeEnum fromValue(String value) {
      for (ItemTypeEnum b : ItemTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ITEM_TYPE = "item_type";
  @javax.annotation.Nonnull
  private ItemTypeEnum itemType;

  public static final String JSON_PROPERTY_GROUPED_BY = "grouped_by";
  @javax.annotation.Nullable
  private Map<String, String> groupedBy = new HashMap<>();

  public FeeObjectItem() {
  }

  public FeeObjectItem type(@javax.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * The fee type. Possible values are &#x60;add-on&#x60;, &#x60;charge&#x60;, &#x60;credit&#x60;, &#x60;subscription&#x60; or &#x60;commitment&#x60;.
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  public FeeObjectItem code(@javax.annotation.Nonnull String code) {
    
    this.code = code;
    return this;
  }

  /**
   * The code of the fee item. It can be the code of the &#x60;add-on&#x60;, the code of the &#x60;charge&#x60;, the code of the &#x60;credit&#x60; or the code of the &#x60;subscription&#x60;.
   * @return code
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }


  public FeeObjectItem name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of the fee item. It can be the name of the &#x60;add-on&#x60;, the &#x60;charge&#x60;, the &#x60;credit&#x60;, the &#x60;subscription&#x60; or the &#x60;commitment&#x60;.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public FeeObjectItem invoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    
    this.invoiceDisplayName = invoiceDisplayName;
    return this;
  }

  /**
   * Specifies the name that will be displayed on an invoice. If no value is set for this field, the name of the actual charge will be used as the default display name.
   * @return invoiceDisplayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInvoiceDisplayName() {
    return invoiceDisplayName;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    this.invoiceDisplayName = invoiceDisplayName;
  }


  public FeeObjectItem filterInvoiceDisplayName(@javax.annotation.Nullable String filterInvoiceDisplayName) {
    
    this.filterInvoiceDisplayName = filterInvoiceDisplayName;
    return this;
  }

  /**
   * Specifies the name that will be displayed on an invoice. If no value is set for this field, the actual charge filter values will be used as the default display name.
   * @return filterInvoiceDisplayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilterInvoiceDisplayName() {
    return filterInvoiceDisplayName;
  }


  @JsonProperty(JSON_PROPERTY_FILTER_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilterInvoiceDisplayName(@javax.annotation.Nullable String filterInvoiceDisplayName) {
    this.filterInvoiceDisplayName = filterInvoiceDisplayName;
  }


  public FeeObjectItem filters(@javax.annotation.Nullable Map<String, List<String>> filters) {
    
    this.filters = filters;
    return this;
  }

  public FeeObjectItem putFiltersItem(String key, List<String> filtersItem) {
    if (this.filters == null) {
      this.filters = new HashMap<>();
    }
    this.filters.put(key, filtersItem);
    return this;
  }

  /**
   * Key value list of event properties
   * @return filters
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<String>> getFilters() {
    return filters;
  }


  @JsonProperty(JSON_PROPERTY_FILTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilters(@javax.annotation.Nullable Map<String, List<String>> filters) {
    this.filters = filters;
  }


  public FeeObjectItem lagoItemId(@javax.annotation.Nonnull UUID lagoItemId) {
    
    this.lagoItemId = lagoItemId;
    return this;
  }

  /**
   * Unique identifier of the fee item, created by Lago. It can be the identifier of the &#x60;add-on&#x60;, the &#x60;charge&#x60;, the &#x60;credit&#x60;, the &#x60;subscription&#x60; or the &#x60;commitment&#x60;.
   * @return lagoItemId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_ITEM_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoItemId() {
    return lagoItemId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_ITEM_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoItemId(@javax.annotation.Nonnull UUID lagoItemId) {
    this.lagoItemId = lagoItemId;
  }


  public FeeObjectItem itemType(@javax.annotation.Nonnull ItemTypeEnum itemType) {
    
    this.itemType = itemType;
    return this;
  }

  /**
   * The type of the fee item. Possible values are &#x60;AddOn&#x60;, &#x60;BillableMetric&#x60;, &#x60;WalletTransaction&#x60;, &#x60;Subscription&#x60; or &#x60;Commitment&#x60;.
   * @return itemType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITEM_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ItemTypeEnum getItemType() {
    return itemType;
  }


  @JsonProperty(JSON_PROPERTY_ITEM_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItemType(@javax.annotation.Nonnull ItemTypeEnum itemType) {
    this.itemType = itemType;
  }


  public FeeObjectItem groupedBy(@javax.annotation.Nullable Map<String, String> groupedBy) {
    
    this.groupedBy = groupedBy;
    return this;
  }

  public FeeObjectItem putGroupedByItem(String key, String groupedByItem) {
    if (this.groupedBy == null) {
      this.groupedBy = new HashMap<>();
    }
    this.groupedBy.put(key, groupedByItem);
    return this;
  }

  /**
   * Key value list of event properties aggregated by the charge model
   * @return groupedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUPED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, String> getGroupedBy() {
    return groupedBy;
  }


  @JsonProperty(JSON_PROPERTY_GROUPED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroupedBy(@javax.annotation.Nullable Map<String, String> groupedBy) {
    this.groupedBy = groupedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeObjectItem feeObjectItem = (FeeObjectItem) o;
    return Objects.equals(this.type, feeObjectItem.type) &&
        Objects.equals(this.code, feeObjectItem.code) &&
        Objects.equals(this.name, feeObjectItem.name) &&
        Objects.equals(this.invoiceDisplayName, feeObjectItem.invoiceDisplayName) &&
        Objects.equals(this.filterInvoiceDisplayName, feeObjectItem.filterInvoiceDisplayName) &&
        Objects.equals(this.filters, feeObjectItem.filters) &&
        Objects.equals(this.lagoItemId, feeObjectItem.lagoItemId) &&
        Objects.equals(this.itemType, feeObjectItem.itemType) &&
        Objects.equals(this.groupedBy, feeObjectItem.groupedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, code, name, invoiceDisplayName, filterInvoiceDisplayName, filters, lagoItemId, itemType, groupedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeObjectItem {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    invoiceDisplayName: ").append(toIndentedString(invoiceDisplayName)).append("\n");
    sb.append("    filterInvoiceDisplayName: ").append(toIndentedString(filterInvoiceDisplayName)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    lagoItemId: ").append(toIndentedString(lagoItemId)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    groupedBy: ").append(toIndentedString(groupedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

