/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.InvoiceObjectExtended;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InvoicePaymentDisputeLostRequest
 */
@JsonPropertyOrder({
  InvoicePaymentDisputeLostRequest.JSON_PROPERTY_WEBHOOK_TYPE,
  InvoicePaymentDisputeLostRequest.JSON_PROPERTY_OBJECT_TYPE,
  InvoicePaymentDisputeLostRequest.JSON_PROPERTY_PAYMENT_DISPUTE_LOST
})
@JsonTypeName("invoicePaymentDisputeLost_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class InvoicePaymentDisputeLostRequest {
  /**
   * Gets or Sets webhookType
   */
  public enum WebhookTypeEnum {
    INVOICE_PAYMENT_DISPUTE_LOST(String.valueOf("invoice.payment_dispute_lost"));

    private String value;

    WebhookTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WebhookTypeEnum fromValue(String value) {
      for (WebhookTypeEnum b : WebhookTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WEBHOOK_TYPE = "webhook_type";
  @javax.annotation.Nonnull
  private WebhookTypeEnum webhookType;

  /**
   * Gets or Sets objectType
   */
  public enum ObjectTypeEnum {
    PAYMENT_DISPUTE_LOST(String.valueOf("payment_dispute_lost"));

    private String value;

    ObjectTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectTypeEnum fromValue(String value) {
      for (ObjectTypeEnum b : ObjectTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT_TYPE = "object_type";
  @javax.annotation.Nonnull
  private ObjectTypeEnum objectType;

  public static final String JSON_PROPERTY_PAYMENT_DISPUTE_LOST = "payment_dispute_lost";
  @javax.annotation.Nonnull
  private InvoiceObjectExtended paymentDisputeLost;

  public InvoicePaymentDisputeLostRequest() {
  }

  public InvoicePaymentDisputeLostRequest webhookType(@javax.annotation.Nonnull WebhookTypeEnum webhookType) {
    
    this.webhookType = webhookType;
    return this;
  }

  /**
   * Get webhookType
   * @return webhookType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WEBHOOK_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WebhookTypeEnum getWebhookType() {
    return webhookType;
  }


  @JsonProperty(JSON_PROPERTY_WEBHOOK_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebhookType(@javax.annotation.Nonnull WebhookTypeEnum webhookType) {
    this.webhookType = webhookType;
  }


  public InvoicePaymentDisputeLostRequest objectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    
    this.objectType = objectType;
    return this;
  }

  /**
   * Get objectType
   * @return objectType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjectTypeEnum getObjectType() {
    return objectType;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    this.objectType = objectType;
  }


  public InvoicePaymentDisputeLostRequest paymentDisputeLost(@javax.annotation.Nonnull InvoiceObjectExtended paymentDisputeLost) {
    
    this.paymentDisputeLost = paymentDisputeLost;
    return this;
  }

  /**
   * Get paymentDisputeLost
   * @return paymentDisputeLost
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_DISPUTE_LOST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public InvoiceObjectExtended getPaymentDisputeLost() {
    return paymentDisputeLost;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_DISPUTE_LOST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentDisputeLost(@javax.annotation.Nonnull InvoiceObjectExtended paymentDisputeLost) {
    this.paymentDisputeLost = paymentDisputeLost;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePaymentDisputeLostRequest invoicePaymentDisputeLostRequest = (InvoicePaymentDisputeLostRequest) o;
    return Objects.equals(this.webhookType, invoicePaymentDisputeLostRequest.webhookType) &&
        Objects.equals(this.objectType, invoicePaymentDisputeLostRequest.objectType) &&
        Objects.equals(this.paymentDisputeLost, invoicePaymentDisputeLostRequest.paymentDisputeLost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhookType, objectType, paymentDisputeLost);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePaymentDisputeLostRequest {\n");
    sb.append("    webhookType: ").append(toIndentedString(webhookType)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    paymentDisputeLost: ").append(toIndentedString(paymentDisputeLost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

