/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LifetimeUsageInputLifetimeUsage
 */
@JsonPropertyOrder({
  LifetimeUsageInputLifetimeUsage.JSON_PROPERTY_EXTERNAL_HISTORICAL_USAGE_AMOUNT_CENTS
})
@JsonTypeName("LifetimeUsageInput_lifetime_usage")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class LifetimeUsageInputLifetimeUsage {
  public static final String JSON_PROPERTY_EXTERNAL_HISTORICAL_USAGE_AMOUNT_CENTS = "external_historical_usage_amount_cents";
  @javax.annotation.Nonnull
  private Integer externalHistoricalUsageAmountCents;

  public LifetimeUsageInputLifetimeUsage() {
  }

  public LifetimeUsageInputLifetimeUsage externalHistoricalUsageAmountCents(@javax.annotation.Nonnull Integer externalHistoricalUsageAmountCents) {
    
    this.externalHistoricalUsageAmountCents = externalHistoricalUsageAmountCents;
    return this;
  }

  /**
   * The historical usage amount in cents for the subscription (provided by your own application).
   * @return externalHistoricalUsageAmountCents
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXTERNAL_HISTORICAL_USAGE_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getExternalHistoricalUsageAmountCents() {
    return externalHistoricalUsageAmountCents;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_HISTORICAL_USAGE_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalHistoricalUsageAmountCents(@javax.annotation.Nonnull Integer externalHistoricalUsageAmountCents) {
    this.externalHistoricalUsageAmountCents = externalHistoricalUsageAmountCents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LifetimeUsageInputLifetimeUsage lifetimeUsageInputLifetimeUsage = (LifetimeUsageInputLifetimeUsage) o;
    return Objects.equals(this.externalHistoricalUsageAmountCents, lifetimeUsageInputLifetimeUsage.externalHistoricalUsageAmountCents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(externalHistoricalUsageAmountCents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LifetimeUsageInputLifetimeUsage {\n");
    sb.append("    externalHistoricalUsageAmountCents: ").append(toIndentedString(externalHistoricalUsageAmountCents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

