/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LifetimeUsageThresholdObject
 */
@JsonPropertyOrder({
  LifetimeUsageThresholdObject.JSON_PROPERTY_AMOUNT_CENTS,
  LifetimeUsageThresholdObject.JSON_PROPERTY_COMPLETION_RATIO,
  LifetimeUsageThresholdObject.JSON_PROPERTY_REACHED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class LifetimeUsageThresholdObject {
  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amount_cents";
  @javax.annotation.Nonnull
  private Integer amountCents;

  public static final String JSON_PROPERTY_COMPLETION_RATIO = "completion_ratio";
  @javax.annotation.Nonnull
  private BigDecimal completionRatio;

  public static final String JSON_PROPERTY_REACHED_AT = "reached_at";
  @javax.annotation.Nullable
  private OffsetDateTime reachedAt;

  public LifetimeUsageThresholdObject() {
  }

  public LifetimeUsageThresholdObject amountCents(@javax.annotation.Nonnull Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * The usage threshold amount in cents.
   * @return amountCents
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountCents(@javax.annotation.Nonnull Integer amountCents) {
    this.amountCents = amountCents;
  }


  public LifetimeUsageThresholdObject completionRatio(@javax.annotation.Nonnull BigDecimal completionRatio) {
    
    this.completionRatio = completionRatio;
    return this;
  }

  /**
   * The completion ratio of the usage threshold.
   * @return completionRatio
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COMPLETION_RATIO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getCompletionRatio() {
    return completionRatio;
  }


  @JsonProperty(JSON_PROPERTY_COMPLETION_RATIO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompletionRatio(@javax.annotation.Nonnull BigDecimal completionRatio) {
    this.completionRatio = completionRatio;
  }


  public LifetimeUsageThresholdObject reachedAt(@javax.annotation.Nullable OffsetDateTime reachedAt) {
    
    this.reachedAt = reachedAt;
    return this;
  }

  /**
   * The date and time when the usage threshold was reached. The date and time must be in ISO 8601 format.
   * @return reachedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REACHED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getReachedAt() {
    return reachedAt;
  }


  @JsonProperty(JSON_PROPERTY_REACHED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReachedAt(@javax.annotation.Nullable OffsetDateTime reachedAt) {
    this.reachedAt = reachedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LifetimeUsageThresholdObject lifetimeUsageThresholdObject = (LifetimeUsageThresholdObject) o;
    return Objects.equals(this.amountCents, lifetimeUsageThresholdObject.amountCents) &&
        Objects.equals(this.completionRatio, lifetimeUsageThresholdObject.completionRatio) &&
        Objects.equals(this.reachedAt, lifetimeUsageThresholdObject.reachedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountCents, completionRatio, reachedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LifetimeUsageThresholdObject {\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    completionRatio: ").append(toIndentedString(completionRatio)).append("\n");
    sb.append("    reachedAt: ").append(toIndentedString(reachedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

