/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Minimum commitment for this plan.
 */
@JsonPropertyOrder({
  MinimumCommitmentInput.JSON_PROPERTY_AMOUNT_CENTS,
  MinimumCommitmentInput.JSON_PROPERTY_INVOICE_DISPLAY_NAME,
  MinimumCommitmentInput.JSON_PROPERTY_TAX_CODES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class MinimumCommitmentInput {
  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amount_cents";
  @javax.annotation.Nonnull
  private Integer amountCents;

  public static final String JSON_PROPERTY_INVOICE_DISPLAY_NAME = "invoice_display_name";
  @javax.annotation.Nullable
  private String invoiceDisplayName;

  public static final String JSON_PROPERTY_TAX_CODES = "tax_codes";
  @javax.annotation.Nullable
  private List<String> taxCodes = new ArrayList<>();

  public MinimumCommitmentInput() {
  }

  public MinimumCommitmentInput amountCents(@javax.annotation.Nonnull Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * The amount of the minimum commitment in cents.
   * @return amountCents
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountCents(@javax.annotation.Nonnull Integer amountCents) {
    this.amountCents = amountCents;
  }


  public MinimumCommitmentInput invoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    
    this.invoiceDisplayName = invoiceDisplayName;
    return this;
  }

  /**
   * Specifies the name that will be displayed on an invoice. If no value is set for this field, the default name will be used as the display name.
   * @return invoiceDisplayName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getInvoiceDisplayName() {
    return invoiceDisplayName;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoiceDisplayName(@javax.annotation.Nullable String invoiceDisplayName) {
    this.invoiceDisplayName = invoiceDisplayName;
  }


  public MinimumCommitmentInput taxCodes(@javax.annotation.Nullable List<String> taxCodes) {
    
    this.taxCodes = taxCodes;
    return this;
  }

  public MinimumCommitmentInput addTaxCodesItem(String taxCodesItem) {
    if (this.taxCodes == null) {
      this.taxCodes = new ArrayList<>();
    }
    this.taxCodes.add(taxCodesItem);
    return this;
  }

  /**
   * List of unique code used to identify the taxes.
   * @return taxCodes
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getTaxCodes() {
    return taxCodes;
  }


  @JsonProperty(JSON_PROPERTY_TAX_CODES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxCodes(@javax.annotation.Nullable List<String> taxCodes) {
    this.taxCodes = taxCodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MinimumCommitmentInput minimumCommitmentInput = (MinimumCommitmentInput) o;
    return Objects.equals(this.amountCents, minimumCommitmentInput.amountCents) &&
        Objects.equals(this.invoiceDisplayName, minimumCommitmentInput.invoiceDisplayName) &&
        Objects.equals(this.taxCodes, minimumCommitmentInput.taxCodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountCents, invoiceDisplayName, taxCodes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MinimumCommitmentInput {\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    invoiceDisplayName: ").append(toIndentedString(invoiceDisplayName)).append("\n");
    sb.append("    taxCodes: ").append(toIndentedString(taxCodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

