/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.PaymentRequestCreateInputPaymentRequest;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PaymentRequestCreateInput
 */
@JsonPropertyOrder({
  PaymentRequestCreateInput.JSON_PROPERTY_PAYMENT_REQUEST
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class PaymentRequestCreateInput {
  public static final String JSON_PROPERTY_PAYMENT_REQUEST = "payment_request";
  @javax.annotation.Nonnull
  private PaymentRequestCreateInputPaymentRequest paymentRequest;

  public PaymentRequestCreateInput() {
  }

  public PaymentRequestCreateInput paymentRequest(@javax.annotation.Nonnull PaymentRequestCreateInputPaymentRequest paymentRequest) {
    
    this.paymentRequest = paymentRequest;
    return this;
  }

  /**
   * Get paymentRequest
   * @return paymentRequest
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PaymentRequestCreateInputPaymentRequest getPaymentRequest() {
    return paymentRequest;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_REQUEST)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentRequest(@javax.annotation.Nonnull PaymentRequestCreateInputPaymentRequest paymentRequest) {
    this.paymentRequest = paymentRequest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequestCreateInput paymentRequestCreateInput = (PaymentRequestCreateInput) o;
    return Objects.equals(this.paymentRequest, paymentRequestCreateInput.paymentRequest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentRequest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequestCreateInput {\n");
    sb.append("    paymentRequest: ").append(toIndentedString(paymentRequest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

