/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.SubscriptionWithCustomerObject;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SubscriptionTerminatedRequest
 */
@JsonPropertyOrder({
  SubscriptionTerminatedRequest.JSON_PROPERTY_WEBHOOK_TYPE,
  SubscriptionTerminatedRequest.JSON_PROPERTY_OBJECT_TYPE,
  SubscriptionTerminatedRequest.JSON_PROPERTY_SUBSCRIPTION
})
@JsonTypeName("subscriptionTerminated_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class SubscriptionTerminatedRequest {
  /**
   * Gets or Sets webhookType
   */
  public enum WebhookTypeEnum {
    SUBSCRIPTION_TERMINATED(String.valueOf("subscription.terminated"));

    private String value;

    WebhookTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static WebhookTypeEnum fromValue(String value) {
      for (WebhookTypeEnum b : WebhookTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_WEBHOOK_TYPE = "webhook_type";
  @javax.annotation.Nonnull
  private WebhookTypeEnum webhookType;

  /**
   * Gets or Sets objectType
   */
  public enum ObjectTypeEnum {
    SUBSCRIPTION(String.valueOf("subscription"));

    private String value;

    ObjectTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ObjectTypeEnum fromValue(String value) {
      for (ObjectTypeEnum b : ObjectTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OBJECT_TYPE = "object_type";
  @javax.annotation.Nonnull
  private ObjectTypeEnum objectType;

  public static final String JSON_PROPERTY_SUBSCRIPTION = "subscription";
  @javax.annotation.Nonnull
  private SubscriptionWithCustomerObject subscription;

  public SubscriptionTerminatedRequest() {
  }

  public SubscriptionTerminatedRequest webhookType(@javax.annotation.Nonnull WebhookTypeEnum webhookType) {
    
    this.webhookType = webhookType;
    return this;
  }

  /**
   * Get webhookType
   * @return webhookType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WEBHOOK_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public WebhookTypeEnum getWebhookType() {
    return webhookType;
  }


  @JsonProperty(JSON_PROPERTY_WEBHOOK_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWebhookType(@javax.annotation.Nonnull WebhookTypeEnum webhookType) {
    this.webhookType = webhookType;
  }


  public SubscriptionTerminatedRequest objectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    
    this.objectType = objectType;
    return this;
  }

  /**
   * Get objectType
   * @return objectType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ObjectTypeEnum getObjectType() {
    return objectType;
  }


  @JsonProperty(JSON_PROPERTY_OBJECT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setObjectType(@javax.annotation.Nonnull ObjectTypeEnum objectType) {
    this.objectType = objectType;
  }


  public SubscriptionTerminatedRequest subscription(@javax.annotation.Nonnull SubscriptionWithCustomerObject subscription) {
    
    this.subscription = subscription;
    return this;
  }

  /**
   * Get subscription
   * @return subscription
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SubscriptionWithCustomerObject getSubscription() {
    return subscription;
  }


  @JsonProperty(JSON_PROPERTY_SUBSCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubscription(@javax.annotation.Nonnull SubscriptionWithCustomerObject subscription) {
    this.subscription = subscription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionTerminatedRequest subscriptionTerminatedRequest = (SubscriptionTerminatedRequest) o;
    return Objects.equals(this.webhookType, subscriptionTerminatedRequest.webhookType) &&
        Objects.equals(this.objectType, subscriptionTerminatedRequest.objectType) &&
        Objects.equals(this.subscription, subscriptionTerminatedRequest.subscription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(webhookType, objectType, subscription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionTerminatedRequest {\n");
    sb.append("    webhookType: ").append(toIndentedString(webhookType)).append("\n");
    sb.append("    objectType: ").append(toIndentedString(objectType)).append("\n");
    sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

