/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UsageThresholdObject
 */
@JsonPropertyOrder({
  UsageThresholdObject.JSON_PROPERTY_LAGO_ID,
  UsageThresholdObject.JSON_PROPERTY_THRESHOLD_DISPLAY_NAME,
  UsageThresholdObject.JSON_PROPERTY_AMOUNT_CENTS,
  UsageThresholdObject.JSON_PROPERTY_RECURRING,
  UsageThresholdObject.JSON_PROPERTY_CREATED_AT,
  UsageThresholdObject.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class UsageThresholdObject {
  public static final String JSON_PROPERTY_LAGO_ID = "lago_id";
  @javax.annotation.Nonnull
  private UUID lagoId;

  public static final String JSON_PROPERTY_THRESHOLD_DISPLAY_NAME = "threshold_display_name";
  private JsonNullable<String> thresholdDisplayName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amount_cents";
  @javax.annotation.Nonnull
  private Integer amountCents;

  public static final String JSON_PROPERTY_RECURRING = "recurring";
  @javax.annotation.Nonnull
  private Boolean recurring;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nonnull
  private OffsetDateTime updatedAt;

  public UsageThresholdObject() {
  }

  public UsageThresholdObject lagoId(@javax.annotation.Nonnull UUID lagoId) {
    
    this.lagoId = lagoId;
    return this;
  }

  /**
   * Unique identifier of the usage threshold created by Lago.
   * @return lagoId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoId() {
    return lagoId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoId(@javax.annotation.Nonnull UUID lagoId) {
    this.lagoId = lagoId;
  }


  public UsageThresholdObject thresholdDisplayName(@javax.annotation.Nullable String thresholdDisplayName) {
    this.thresholdDisplayName = JsonNullable.<String>of(thresholdDisplayName);
    
    return this;
  }

  /**
   * The display name of the usage threshold.
   * @return thresholdDisplayName
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getThresholdDisplayName() {
        return thresholdDisplayName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_THRESHOLD_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getThresholdDisplayName_JsonNullable() {
    return thresholdDisplayName;
  }
  
  @JsonProperty(JSON_PROPERTY_THRESHOLD_DISPLAY_NAME)
  public void setThresholdDisplayName_JsonNullable(JsonNullable<String> thresholdDisplayName) {
    this.thresholdDisplayName = thresholdDisplayName;
  }

  public void setThresholdDisplayName(@javax.annotation.Nullable String thresholdDisplayName) {
    this.thresholdDisplayName = JsonNullable.<String>of(thresholdDisplayName);
  }


  public UsageThresholdObject amountCents(@javax.annotation.Nonnull Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * The amount to reach to trigger a &#x60;progressive_billing&#x60; invoice.
   * @return amountCents
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountCents(@javax.annotation.Nonnull Integer amountCents) {
    this.amountCents = amountCents;
  }


  public UsageThresholdObject recurring(@javax.annotation.Nonnull Boolean recurring) {
    
    this.recurring = recurring;
    return this;
  }

  /**
   * This field when set to &#x60;true&#x60; indicates that a &#x60;progressive_billing&#x60; invoice will be created every time the lifetime usage increases by the specified amount.
   * @return recurring
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECURRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getRecurring() {
    return recurring;
  }


  @JsonProperty(JSON_PROPERTY_RECURRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecurring(@javax.annotation.Nonnull Boolean recurring) {
    this.recurring = recurring;
  }


  public UsageThresholdObject createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date and time when the usage threshold was created. It is expressed in UTC format according to the ISO 8601 datetime standard.
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public UsageThresholdObject updatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * The date and time when the usage threshold was last updated. It is expressed in UTC format according to the ISO 8601 datetime standard.
   * @return updatedAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUpdatedAt(@javax.annotation.Nonnull OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageThresholdObject usageThresholdObject = (UsageThresholdObject) o;
    return Objects.equals(this.lagoId, usageThresholdObject.lagoId) &&
        equalsNullable(this.thresholdDisplayName, usageThresholdObject.thresholdDisplayName) &&
        Objects.equals(this.amountCents, usageThresholdObject.amountCents) &&
        Objects.equals(this.recurring, usageThresholdObject.recurring) &&
        Objects.equals(this.createdAt, usageThresholdObject.createdAt) &&
        Objects.equals(this.updatedAt, usageThresholdObject.updatedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(lagoId, hashCodeNullable(thresholdDisplayName), amountCents, recurring, createdAt, updatedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageThresholdObject {\n");
    sb.append("    lagoId: ").append(toIndentedString(lagoId)).append("\n");
    sb.append("    thresholdDisplayName: ").append(toIndentedString(thresholdDisplayName)).append("\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    recurring: ").append(toIndentedString(recurring)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

