/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UsageThresholdInput
 */
@JsonPropertyOrder({
  UsageThresholdInput.JSON_PROPERTY_ID,
  UsageThresholdInput.JSON_PROPERTY_THRESHOLD_DISPLAY_NAME,
  UsageThresholdInput.JSON_PROPERTY_AMOUNT_CENTS,
  UsageThresholdInput.JSON_PROPERTY_RECURRING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class UsageThresholdInput {
  public static final String JSON_PROPERTY_ID = "id";
  private JsonNullable<UUID> id = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_THRESHOLD_DISPLAY_NAME = "threshold_display_name";
  private JsonNullable<String> thresholdDisplayName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amount_cents";
  @javax.annotation.Nonnull
  private Integer amountCents;

  public static final String JSON_PROPERTY_RECURRING = "recurring";
  @javax.annotation.Nonnull
  private Boolean recurring;

  public UsageThresholdInput() {
  }

  public UsageThresholdInput id(@javax.annotation.Nullable UUID id) {
    this.id = JsonNullable.<UUID>of(id);
    
    return this;
  }

  /**
   * Unique identifier of the usage threshold created by Lago.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public UUID getId() {
        return id.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getId_JsonNullable() {
    return id;
  }
  
  @JsonProperty(JSON_PROPERTY_ID)
  public void setId_JsonNullable(JsonNullable<UUID> id) {
    this.id = id;
  }

  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = JsonNullable.<UUID>of(id);
  }


  public UsageThresholdInput thresholdDisplayName(@javax.annotation.Nullable String thresholdDisplayName) {
    this.thresholdDisplayName = JsonNullable.<String>of(thresholdDisplayName);
    
    return this;
  }

  /**
   * The display name of the usage threshold.
   * @return thresholdDisplayName
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getThresholdDisplayName() {
        return thresholdDisplayName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_THRESHOLD_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getThresholdDisplayName_JsonNullable() {
    return thresholdDisplayName;
  }
  
  @JsonProperty(JSON_PROPERTY_THRESHOLD_DISPLAY_NAME)
  public void setThresholdDisplayName_JsonNullable(JsonNullable<String> thresholdDisplayName) {
    this.thresholdDisplayName = thresholdDisplayName;
  }

  public void setThresholdDisplayName(@javax.annotation.Nullable String thresholdDisplayName) {
    this.thresholdDisplayName = JsonNullable.<String>of(thresholdDisplayName);
  }


  public UsageThresholdInput amountCents(@javax.annotation.Nonnull Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * The amount to reach to trigger a &#x60;progressive_billing&#x60; invoice.
   * @return amountCents
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountCents(@javax.annotation.Nonnull Integer amountCents) {
    this.amountCents = amountCents;
  }


  public UsageThresholdInput recurring(@javax.annotation.Nonnull Boolean recurring) {
    
    this.recurring = recurring;
    return this;
  }

  /**
   * This field when set to &#x60;true&#x60; indicates that a &#x60;progressive_billing&#x60; invoice will be created every time the lifetime usage increases by the specified amount.
   * @return recurring
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECURRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getRecurring() {
    return recurring;
  }


  @JsonProperty(JSON_PROPERTY_RECURRING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecurring(@javax.annotation.Nonnull Boolean recurring) {
    this.recurring = recurring;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsageThresholdInput usageThresholdInput = (UsageThresholdInput) o;
    return equalsNullable(this.id, usageThresholdInput.id) &&
        equalsNullable(this.thresholdDisplayName, usageThresholdInput.thresholdDisplayName) &&
        Objects.equals(this.amountCents, usageThresholdInput.amountCents) &&
        Objects.equals(this.recurring, usageThresholdInput.recurring);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(id), hashCodeNullable(thresholdDisplayName), amountCents, recurring);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsageThresholdInput {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    thresholdDisplayName: ").append(toIndentedString(thresholdDisplayName)).append("\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    recurring: ").append(toIndentedString(recurring)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

