/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.WalletRecurringTransactionRuleTransactionMetadataInner;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WalletTransactionObject
 */
@JsonPropertyOrder({
  WalletTransactionObject.JSON_PROPERTY_LAGO_ID,
  WalletTransactionObject.JSON_PROPERTY_LAGO_WALLET_ID,
  WalletTransactionObject.JSON_PROPERTY_STATUS,
  WalletTransactionObject.JSON_PROPERTY_SOURCE,
  WalletTransactionObject.JSON_PROPERTY_TRANSACTION_STATUS,
  WalletTransactionObject.JSON_PROPERTY_TRANSACTION_TYPE,
  WalletTransactionObject.JSON_PROPERTY_AMOUNT,
  WalletTransactionObject.JSON_PROPERTY_CREDIT_AMOUNT,
  WalletTransactionObject.JSON_PROPERTY_INVOICE_REQUIRES_SUCCESSFUL_PAYMENT,
  WalletTransactionObject.JSON_PROPERTY_METADATA,
  WalletTransactionObject.JSON_PROPERTY_SETTLED_AT,
  WalletTransactionObject.JSON_PROPERTY_FAILED_AT,
  WalletTransactionObject.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class WalletTransactionObject {
  public static final String JSON_PROPERTY_LAGO_ID = "lago_id";
  @javax.annotation.Nonnull
  private UUID lagoId;

  public static final String JSON_PROPERTY_LAGO_WALLET_ID = "lago_wallet_id";
  @javax.annotation.Nonnull
  private UUID lagoWalletId;

  /**
   * The status of the wallet transaction. Possible values are &#x60;pending&#x60;, &#x60;settled&#x60; or &#x60;failed&#x60;.
   */
  public enum StatusEnum {
    PENDING(String.valueOf("pending")),
    
    SETTLED(String.valueOf("settled")),
    
    FAILED(String.valueOf("failed"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private StatusEnum status;

  /**
   * The source field represents the origin or trigger of the wallet transaction. Possible values are &#x60;manual&#x60;, &#x60;interval&#x60;. &#x60;threshold&#x60;
   */
  public enum SourceEnum {
    MANUAL(String.valueOf("manual")),
    
    INTERVAL(String.valueOf("interval")),
    
    THRESHOLD(String.valueOf("threshold"));

    private String value;

    SourceEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SourceEnum fromValue(String value) {
      for (SourceEnum b : SourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_SOURCE = "source";
  @javax.annotation.Nullable
  private SourceEnum source;

  /**
   * The transaction status of the wallet transaction. Possible values are &#x60;purchased&#x60; (with pending or settled status), &#x60;granted&#x60; (without invoice_id), &#x60;voided&#x60; or &#x60;invoiced&#x60;.
   */
  public enum TransactionStatusEnum {
    PURCHASED(String.valueOf("purchased")),
    
    GRANTED(String.valueOf("granted")),
    
    VOIDED(String.valueOf("voided")),
    
    INVOICED(String.valueOf("invoiced"));

    private String value;

    TransactionStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TransactionStatusEnum fromValue(String value) {
      for (TransactionStatusEnum b : TransactionStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TRANSACTION_STATUS = "transaction_status";
  @javax.annotation.Nonnull
  private TransactionStatusEnum transactionStatus;

  /**
   * The type of transaction. Possible values are &#x60;inbound&#x60; (increasing the balance) or &#x60;outbound&#x60; (decreasing the balance).
   */
  public enum TransactionTypeEnum {
    INBOUND(String.valueOf("inbound")),
    
    OUTBOUND(String.valueOf("outbound"));

    private String value;

    TransactionTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TransactionTypeEnum fromValue(String value) {
      for (TransactionTypeEnum b : TransactionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transaction_type";
  @javax.annotation.Nonnull
  private TransactionTypeEnum transactionType;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private String amount;

  public static final String JSON_PROPERTY_CREDIT_AMOUNT = "credit_amount";
  @javax.annotation.Nonnull
  private String creditAmount;

  public static final String JSON_PROPERTY_INVOICE_REQUIRES_SUCCESSFUL_PAYMENT = "invoice_requires_successful_payment";
  @javax.annotation.Nullable
  private Boolean invoiceRequiresSuccessfulPayment;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private List<WalletRecurringTransactionRuleTransactionMetadataInner> metadata = new ArrayList<>();

  public static final String JSON_PROPERTY_SETTLED_AT = "settled_at";
  @javax.annotation.Nullable
  private OffsetDateTime settledAt;

  public static final String JSON_PROPERTY_FAILED_AT = "failed_at";
  @javax.annotation.Nullable
  private OffsetDateTime failedAt;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public WalletTransactionObject() {
  }

  public WalletTransactionObject lagoId(@javax.annotation.Nonnull UUID lagoId) {
    
    this.lagoId = lagoId;
    return this;
  }

  /**
   * Unique identifier assigned to the wallet transaction within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the wallet transaction&#39;s record within the Lago system.
   * @return lagoId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoId() {
    return lagoId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoId(@javax.annotation.Nonnull UUID lagoId) {
    this.lagoId = lagoId;
  }


  public WalletTransactionObject lagoWalletId(@javax.annotation.Nonnull UUID lagoWalletId) {
    
    this.lagoWalletId = lagoWalletId;
    return this;
  }

  /**
   * Unique identifier assigned to the wallet within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the wallet&#39;s record within the Lago system.
   * @return lagoWalletId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_WALLET_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoWalletId() {
    return lagoWalletId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_WALLET_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoWalletId(@javax.annotation.Nonnull UUID lagoWalletId) {
    this.lagoWalletId = lagoWalletId;
  }


  public WalletTransactionObject status(@javax.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * The status of the wallet transaction. Possible values are &#x60;pending&#x60;, &#x60;settled&#x60; or &#x60;failed&#x60;.
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }


  public WalletTransactionObject source(@javax.annotation.Nullable SourceEnum source) {
    
    this.source = source;
    return this;
  }

  /**
   * The source field represents the origin or trigger of the wallet transaction. Possible values are &#x60;manual&#x60;, &#x60;interval&#x60;. &#x60;threshold&#x60;
   * @return source
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public SourceEnum getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@javax.annotation.Nullable SourceEnum source) {
    this.source = source;
  }


  public WalletTransactionObject transactionStatus(@javax.annotation.Nonnull TransactionStatusEnum transactionStatus) {
    
    this.transactionStatus = transactionStatus;
    return this;
  }

  /**
   * The transaction status of the wallet transaction. Possible values are &#x60;purchased&#x60; (with pending or settled status), &#x60;granted&#x60; (without invoice_id), &#x60;voided&#x60; or &#x60;invoiced&#x60;.
   * @return transactionStatus
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransactionStatusEnum getTransactionStatus() {
    return transactionStatus;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionStatus(@javax.annotation.Nonnull TransactionStatusEnum transactionStatus) {
    this.transactionStatus = transactionStatus;
  }


  public WalletTransactionObject transactionType(@javax.annotation.Nonnull TransactionTypeEnum transactionType) {
    
    this.transactionType = transactionType;
    return this;
  }

  /**
   * The type of transaction. Possible values are &#x60;inbound&#x60; (increasing the balance) or &#x60;outbound&#x60; (decreasing the balance).
   * @return transactionType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TransactionTypeEnum getTransactionType() {
    return transactionType;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionType(@javax.annotation.Nonnull TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
  }


  public WalletTransactionObject amount(@javax.annotation.Nonnull String amount) {
    
    this.amount = amount;
    return this;
  }

  /**
   * The amount of credits based on the rate and the currency.
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAmount() {
    return amount;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull String amount) {
    this.amount = amount;
  }


  public WalletTransactionObject creditAmount(@javax.annotation.Nonnull String creditAmount) {
    
    this.creditAmount = creditAmount;
    return this;
  }

  /**
   * The number of credits used in the wallet transaction.
   * @return creditAmount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREDIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCreditAmount() {
    return creditAmount;
  }


  @JsonProperty(JSON_PROPERTY_CREDIT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreditAmount(@javax.annotation.Nonnull String creditAmount) {
    this.creditAmount = creditAmount;
  }


  public WalletTransactionObject invoiceRequiresSuccessfulPayment(@javax.annotation.Nullable Boolean invoiceRequiresSuccessfulPayment) {
    
    this.invoiceRequiresSuccessfulPayment = invoiceRequiresSuccessfulPayment;
    return this;
  }

  /**
   * A boolean setting that, when set to true, delays issuing an invoice for a wallet top-up until a successful payment is made; if false, the invoice is issued immediately upon wallet top-up, regardless of the payment status. Default value of false.
   * @return invoiceRequiresSuccessfulPayment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVOICE_REQUIRES_SUCCESSFUL_PAYMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInvoiceRequiresSuccessfulPayment() {
    return invoiceRequiresSuccessfulPayment;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE_REQUIRES_SUCCESSFUL_PAYMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvoiceRequiresSuccessfulPayment(@javax.annotation.Nullable Boolean invoiceRequiresSuccessfulPayment) {
    this.invoiceRequiresSuccessfulPayment = invoiceRequiresSuccessfulPayment;
  }


  public WalletTransactionObject metadata(@javax.annotation.Nullable List<WalletRecurringTransactionRuleTransactionMetadataInner> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public WalletTransactionObject addMetadataItem(WalletRecurringTransactionRuleTransactionMetadataInner metadataItem) {
    if (this.metadata == null) {
      this.metadata = new ArrayList<>();
    }
    this.metadata.add(metadataItem);
    return this;
  }

  /**
   * This field allows you to store a list of key-value pairs that hold additional information or custom attributes related to the data.
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<WalletRecurringTransactionRuleTransactionMetadataInner> getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable List<WalletRecurringTransactionRuleTransactionMetadataInner> metadata) {
    this.metadata = metadata;
  }


  public WalletTransactionObject settledAt(@javax.annotation.Nullable OffsetDateTime settledAt) {
    
    this.settledAt = settledAt;
    return this;
  }

  /**
   * The date when wallet transaction is settled, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC).
   * @return settledAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SETTLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getSettledAt() {
    return settledAt;
  }


  @JsonProperty(JSON_PROPERTY_SETTLED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSettledAt(@javax.annotation.Nullable OffsetDateTime settledAt) {
    this.settledAt = settledAt;
  }


  public WalletTransactionObject failedAt(@javax.annotation.Nullable OffsetDateTime failedAt) {
    
    this.failedAt = failedAt;
    return this;
  }

  /**
   * The date when the wallet transaction failed, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC).
   * @return failedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FAILED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getFailedAt() {
    return failedAt;
  }


  @JsonProperty(JSON_PROPERTY_FAILED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailedAt(@javax.annotation.Nullable OffsetDateTime failedAt) {
    this.failedAt = failedAt;
  }


  public WalletTransactionObject createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * The date of the wallet transaction creation, represented in ISO 8601 datetime format and expressed in Coordinated Universal Time (UTC).
   * @return createdAt
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletTransactionObject walletTransactionObject = (WalletTransactionObject) o;
    return Objects.equals(this.lagoId, walletTransactionObject.lagoId) &&
        Objects.equals(this.lagoWalletId, walletTransactionObject.lagoWalletId) &&
        Objects.equals(this.status, walletTransactionObject.status) &&
        Objects.equals(this.source, walletTransactionObject.source) &&
        Objects.equals(this.transactionStatus, walletTransactionObject.transactionStatus) &&
        Objects.equals(this.transactionType, walletTransactionObject.transactionType) &&
        Objects.equals(this.amount, walletTransactionObject.amount) &&
        Objects.equals(this.creditAmount, walletTransactionObject.creditAmount) &&
        Objects.equals(this.invoiceRequiresSuccessfulPayment, walletTransactionObject.invoiceRequiresSuccessfulPayment) &&
        Objects.equals(this.metadata, walletTransactionObject.metadata) &&
        Objects.equals(this.settledAt, walletTransactionObject.settledAt) &&
        Objects.equals(this.failedAt, walletTransactionObject.failedAt) &&
        Objects.equals(this.createdAt, walletTransactionObject.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lagoId, lagoWalletId, status, source, transactionStatus, transactionType, amount, creditAmount, invoiceRequiresSuccessfulPayment, metadata, settledAt, failedAt, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletTransactionObject {\n");
    sb.append("    lagoId: ").append(toIndentedString(lagoId)).append("\n");
    sb.append("    lagoWalletId: ").append(toIndentedString(lagoWalletId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    transactionStatus: ").append(toIndentedString(transactionStatus)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    creditAmount: ").append(toIndentedString(creditAmount)).append("\n");
    sb.append("    invoiceRequiresSuccessfulPayment: ").append(toIndentedString(invoiceRequiresSuccessfulPayment)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    settledAt: ").append(toIndentedString(settledAt)).append("\n");
    sb.append("    failedAt: ").append(toIndentedString(failedAt)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

