/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import org.openapitools.client.model.CustomerIntegratrionErrorObjectProviderError;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * WalletTransactionPaymentFailureObject
 */
@JsonPropertyOrder({
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_LAGO_WALLET_TRANSACTION_ID,
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_LAGO_CUSTOMER_ID,
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_EXTERNAL_CUSTOMER_ID,
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_PROVIDER_CUSTOMER_ID,
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_PAYMENT_PROVIDER,
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_PAYMENT_PROVIDER_CODE,
  WalletTransactionPaymentFailureObject.JSON_PROPERTY_PROVIDER_ERROR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class WalletTransactionPaymentFailureObject {
  public static final String JSON_PROPERTY_LAGO_WALLET_TRANSACTION_ID = "lago_wallet_transaction_id";
  @javax.annotation.Nonnull
  private UUID lagoWalletTransactionId;

  public static final String JSON_PROPERTY_LAGO_CUSTOMER_ID = "lago_customer_id";
  @javax.annotation.Nonnull
  private UUID lagoCustomerId;

  public static final String JSON_PROPERTY_EXTERNAL_CUSTOMER_ID = "external_customer_id";
  @javax.annotation.Nonnull
  private String externalCustomerId;

  public static final String JSON_PROPERTY_PROVIDER_CUSTOMER_ID = "provider_customer_id";
  @javax.annotation.Nullable
  private String providerCustomerId;

  /**
   * The type of payment provider code
   */
  public enum PaymentProviderEnum {
    ADYEN(String.valueOf("adyen")),
    
    CASHFREE(String.valueOf("cashfree")),
    
    GOCARDLESS(String.valueOf("gocardless")),
    
    STRIPE(String.valueOf("stripe"));

    private String value;

    PaymentProviderEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PaymentProviderEnum fromValue(String value) {
      for (PaymentProviderEnum b : PaymentProviderEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PAYMENT_PROVIDER = "payment_provider";
  @javax.annotation.Nonnull
  private PaymentProviderEnum paymentProvider;

  public static final String JSON_PROPERTY_PAYMENT_PROVIDER_CODE = "payment_provider_code";
  @javax.annotation.Nullable
  private String paymentProviderCode;

  public static final String JSON_PROPERTY_PROVIDER_ERROR = "provider_error";
  @javax.annotation.Nullable
  private CustomerIntegratrionErrorObjectProviderError providerError;

  public WalletTransactionPaymentFailureObject() {
  }

  public WalletTransactionPaymentFailureObject lagoWalletTransactionId(@javax.annotation.Nonnull UUID lagoWalletTransactionId) {
    
    this.lagoWalletTransactionId = lagoWalletTransactionId;
    return this;
  }

  /**
   * Unique identifier assigned to the wallet transaction within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the wallet transaction&#39;s record within the Lago system.
   * @return lagoWalletTransactionId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_WALLET_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoWalletTransactionId() {
    return lagoWalletTransactionId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_WALLET_TRANSACTION_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoWalletTransactionId(@javax.annotation.Nonnull UUID lagoWalletTransactionId) {
    this.lagoWalletTransactionId = lagoWalletTransactionId;
  }


  public WalletTransactionPaymentFailureObject lagoCustomerId(@javax.annotation.Nonnull UUID lagoCustomerId) {
    
    this.lagoCustomerId = lagoCustomerId;
    return this;
  }

  /**
   * Unique identifier assigned to the customer within the Lago application. This ID is exclusively created by Lago and serves as a unique identifier for the customer&#39;s record within the Lago system.
   * @return lagoCustomerId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAGO_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getLagoCustomerId() {
    return lagoCustomerId;
  }


  @JsonProperty(JSON_PROPERTY_LAGO_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLagoCustomerId(@javax.annotation.Nonnull UUID lagoCustomerId) {
    this.lagoCustomerId = lagoCustomerId;
  }


  public WalletTransactionPaymentFailureObject externalCustomerId(@javax.annotation.Nonnull String externalCustomerId) {
    
    this.externalCustomerId = externalCustomerId;
    return this;
  }

  /**
   * The customer external unique identifier (provided by your own application)
   * @return externalCustomerId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EXTERNAL_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExternalCustomerId() {
    return externalCustomerId;
  }


  @JsonProperty(JSON_PROPERTY_EXTERNAL_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExternalCustomerId(@javax.annotation.Nonnull String externalCustomerId) {
    this.externalCustomerId = externalCustomerId;
  }


  public WalletTransactionPaymentFailureObject providerCustomerId(@javax.annotation.Nullable String providerCustomerId) {
    
    this.providerCustomerId = providerCustomerId;
    return this;
  }

  /**
   * Unique identifier of the customer within the payment provider
   * @return providerCustomerId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProviderCustomerId() {
    return providerCustomerId;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderCustomerId(@javax.annotation.Nullable String providerCustomerId) {
    this.providerCustomerId = providerCustomerId;
  }


  public WalletTransactionPaymentFailureObject paymentProvider(@javax.annotation.Nonnull PaymentProviderEnum paymentProvider) {
    
    this.paymentProvider = paymentProvider;
    return this;
  }

  /**
   * The type of payment provider code
   * @return paymentProvider
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PaymentProviderEnum getPaymentProvider() {
    return paymentProvider;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PROVIDER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPaymentProvider(@javax.annotation.Nonnull PaymentProviderEnum paymentProvider) {
    this.paymentProvider = paymentProvider;
  }


  public WalletTransactionPaymentFailureObject paymentProviderCode(@javax.annotation.Nullable String paymentProviderCode) {
    
    this.paymentProviderCode = paymentProviderCode;
    return this;
  }

  /**
   * Code of the payment provider
   * @return paymentProviderCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_PROVIDER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentProviderCode() {
    return paymentProviderCode;
  }


  @JsonProperty(JSON_PROPERTY_PAYMENT_PROVIDER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentProviderCode(@javax.annotation.Nullable String paymentProviderCode) {
    this.paymentProviderCode = paymentProviderCode;
  }


  public WalletTransactionPaymentFailureObject providerError(@javax.annotation.Nullable CustomerIntegratrionErrorObjectProviderError providerError) {
    
    this.providerError = providerError;
    return this;
  }

  /**
   * Get providerError
   * @return providerError
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVIDER_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CustomerIntegratrionErrorObjectProviderError getProviderError() {
    return providerError;
  }


  @JsonProperty(JSON_PROPERTY_PROVIDER_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProviderError(@javax.annotation.Nullable CustomerIntegratrionErrorObjectProviderError providerError) {
    this.providerError = providerError;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletTransactionPaymentFailureObject walletTransactionPaymentFailureObject = (WalletTransactionPaymentFailureObject) o;
    return Objects.equals(this.lagoWalletTransactionId, walletTransactionPaymentFailureObject.lagoWalletTransactionId) &&
        Objects.equals(this.lagoCustomerId, walletTransactionPaymentFailureObject.lagoCustomerId) &&
        Objects.equals(this.externalCustomerId, walletTransactionPaymentFailureObject.externalCustomerId) &&
        Objects.equals(this.providerCustomerId, walletTransactionPaymentFailureObject.providerCustomerId) &&
        Objects.equals(this.paymentProvider, walletTransactionPaymentFailureObject.paymentProvider) &&
        Objects.equals(this.paymentProviderCode, walletTransactionPaymentFailureObject.paymentProviderCode) &&
        Objects.equals(this.providerError, walletTransactionPaymentFailureObject.providerError);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lagoWalletTransactionId, lagoCustomerId, externalCustomerId, providerCustomerId, paymentProvider, paymentProviderCode, providerError);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletTransactionPaymentFailureObject {\n");
    sb.append("    lagoWalletTransactionId: ").append(toIndentedString(lagoWalletTransactionId)).append("\n");
    sb.append("    lagoCustomerId: ").append(toIndentedString(lagoCustomerId)).append("\n");
    sb.append("    externalCustomerId: ").append(toIndentedString(externalCustomerId)).append("\n");
    sb.append("    providerCustomerId: ").append(toIndentedString(providerCustomerId)).append("\n");
    sb.append("    paymentProvider: ").append(toIndentedString(paymentProvider)).append("\n");
    sb.append("    paymentProviderCode: ").append(toIndentedString(paymentProviderCode)).append("\n");
    sb.append("    providerError: ").append(toIndentedString(providerError)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

