/*
 * Lago API documentation
 * Lago API allows your application to push customer information and metrics (events) from your application to the billing application.
 *
 * The version of the OpenAPI document: 1.28.1
 * Contact: tech@getlago.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.WalletTransactionPaymentUrlWalletTransactionPaymentDetails;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * .
 */
@JsonPropertyOrder({
  WalletTransactionPaymentUrl.JSON_PROPERTY_WALLET_TRANSACTION_PAYMENT_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-23T15:05:45.180675+03:00[Europe/Kiev]", comments = "Generator version: 7.13.0")
public class WalletTransactionPaymentUrl {
  public static final String JSON_PROPERTY_WALLET_TRANSACTION_PAYMENT_DETAILS = "wallet_transaction_payment_details";
  @javax.annotation.Nullable
  private WalletTransactionPaymentUrlWalletTransactionPaymentDetails walletTransactionPaymentDetails;

  public WalletTransactionPaymentUrl() {
  }

  public WalletTransactionPaymentUrl walletTransactionPaymentDetails(@javax.annotation.Nullable WalletTransactionPaymentUrlWalletTransactionPaymentDetails walletTransactionPaymentDetails) {
    
    this.walletTransactionPaymentDetails = walletTransactionPaymentDetails;
    return this;
  }

  /**
   * Get walletTransactionPaymentDetails
   * @return walletTransactionPaymentDetails
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WALLET_TRANSACTION_PAYMENT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public WalletTransactionPaymentUrlWalletTransactionPaymentDetails getWalletTransactionPaymentDetails() {
    return walletTransactionPaymentDetails;
  }


  @JsonProperty(JSON_PROPERTY_WALLET_TRANSACTION_PAYMENT_DETAILS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWalletTransactionPaymentDetails(@javax.annotation.Nullable WalletTransactionPaymentUrlWalletTransactionPaymentDetails walletTransactionPaymentDetails) {
    this.walletTransactionPaymentDetails = walletTransactionPaymentDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WalletTransactionPaymentUrl walletTransactionPaymentUrl = (WalletTransactionPaymentUrl) o;
    return Objects.equals(this.walletTransactionPaymentDetails, walletTransactionPaymentUrl.walletTransactionPaymentDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(walletTransactionPaymentDetails);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WalletTransactionPaymentUrl {\n");
    sb.append("    walletTransactionPaymentDetails: ").append(toIndentedString(walletTransactionPaymentDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

